- package-lock.json
- package.json
Typo in branch name, moest #16 zijn.
> #16: package.json access-sniff update to 3.1.0

- src/styles/mixins/_dso-variables.scss
> #136 Fix expected font path to match actual font path

- components/dso.scss
- src/styles/components/_selectables.scss
- box-shadow inset + border-radius ie11 fix
> #149 - Checkbox display in IE 11

- src/styles/components/_button.scss
> #186.Tertiare-button-16px : font verkleining

- src/styles/components/_accordion.scss
> #185.accordeon-font-size : font 18px -> 20px

- CHANGELOG.md
- src/styles/components/_button.scss
- src/styles/mixins/_dso-variables.scss
Added margin-bottom for correct cross-browser display
> #193.dikte-lijnen-secundaire-button

- CHANGELOG.md
- components/04-indicators/label/label.config.js
- components/04-indicators/label/label.hbs
- src/styles/components/_label.scss
#194.Label-spacing-padding-too-small : removed extra tag, changed floating to button
> #194.label spacing padding too small

- .fractal/statics/custom-mandelbrot-stylesheet.css
- CHANGELOG.md
Fix gemaakt zodat de hoogte van het content panel goed berekend wordt.
> #208.scrollbugfirefox

- src/styles/components/_pagination.scss
#31 pagination redesign : aanpassing hover/focus stijl en font moet bold.
> #31 pagination redesign

- src/styles/components/_badge.scss
https://infoprojects.atlassian.net/browse/DSOCOMLIB-198
> #269 : Verkleinen fontsize badge naar 14px/.875em

- components/03-forms/10-misc/01-buttons/_buttons.scss
- components/03-forms/10-misc/01-buttons/buttons.config.yml
- components/03-forms/10-misc/01-buttons/buttons.hbs
- reference/render/buttons.html
- src/styles/components/_button.scss
- src/styles/mixins/_dso-variables.scss
@tfrijsewijk `font-weight: 500` is afhankelijk of we wel of niet de nieuwste versie van het font aan de gang krijgen.
> #308.button redesign

- CHANGELOG.md
- src/styles/components/_accordion.scss
- src/styles/components/_anchor.scss
- src/styles/components/_breadcrumbs.scss
- src/styles/components/_button.scss
- src/styles/components/_dropdown.scss
- src/styles/components/_footer.scss
- src/styles/components/_form.scss
- src/styles/components/_header.scss
- src/styles/components/_highlight-box.scss
- src/styles/components/_info.scss
- src/styles/components/_modal.scss
- src/styles/components/_navs.scss
- src/styles/components/_pager.scss
- src/styles/components/_search-bar.scss
- src/styles/components/_selectables.scss
- src/styles/components/_shopping-cart.scss
- src/styles/components/form/_files.scss
- src/styles/mixins/_dso-variables.scss
Hee zo te zien is het nu gelukt met de hulp van een developer. Ik heb all meerdere focus states aangemaakt op meerdere componenten maar het lijkt me slim om gewoon deze even eerst te onderzoeken. 
Als hier algemene pointers op komen die ik moet aanpassen dan ga ik daar mee aan de slag voordat ik de rest ga committen.
> #367 Consistente focus states

- CHANGELOG.md
- components/02-content/highlight-box/highlight-box.config.yml
- components/02-content/highlight-box/highlight-box.js
- reference/render/highlight-box--bordered.html
- reference/render/highlight-box--default.html
- reference/render/highlight-box--icon-indicator.html
- reference/render/highlight-box--step-indicator.html
- reference/render/highlight-box--white-drop-shadow.html
- reference/render/highlight-box--yellow.html
- reference/render/highlight-box.html
- reference/render/rich-content.html
- reference/render/row-equal-heights.html
- reference/render/stappenteller.html
- src/styles/components/_anchor.scss
- src/styles/components/_equal-heights.scss
- src/styles/components/_highlight-box.scss
- src/styles/components/_rich-content.scss
- src/styles/components/_step-counter.scss
> #369 highlight-box prefixen met dso-

- CHANGELOG.md
- src/styles/components/_modal.scss
In sluitknop van modal is het icoon niet netjes gecentreerd #447
> #447: In sluitknop van modal is het icoon niet netjes gecentreerd

- CHANGELOG.md
- components/02-content/shopping-cart/shopping-cart.hbs
- reference/render/shopping-cart--no-toggle.html
- reference/render/shopping-cart--open.html
- reference/render/shopping-cart.html
Shopping kart toelichting mist icoon in lopende tekst #445
> #445: Shopping kart toelichting mist icoon in lopende tekst

- CHANGELOG.md
- src/styles/components/_info.scss
https://github.com/dso-toolkit/dso-toolkit/issues/441
> #441: Uitlijning info-button met tekst is onjuist

- .npmignore
- .travis.yml
- package-lock.json
- package.json
In #375 is branch deployments gerealiseerd. Releases worden intern bij InfoProjects uitgerold. Deze routine kan beter met GitHub/Travis geregeld worden.
> #375 Branch deployments

- CHANGELOG.md
- package-lock.json
- package.json
Vervangt https://github.com/dso-toolkit/dso-toolkit/pull/527
> #522 Gebruik laatste versie van bootstrap-sass : 3.3.7 -> 3.4.1

- CHANGELOG.md
- src/styles/components/_form.scss
Deze PR vervangt https://github.com/dso-toolkit/dso-toolkit/pull/543
> #518 fieldset legend margins font styling

- CHANGELOG.md
- components/02-content/description/_preview.hbs
- components/07-layout/layout.config.yml
- components/07-layout/layout.hbs
- reference/render/layout.html
- src/styles/mixins/_bootstrap-variables.scss
- Aanpassing bootstrap container width variabelen
- Aanpassing layout.hbs voor voorbeeld
> #420 - Responsive layout voorbereiding

- CHANGELOG.md
- components/02-content/cards/cards.config.yml
- components/02-content/cards/cards.hbs
- reference/render/cards--flat.html
- src/styles/components/_card.scss
- Cards component variant zonder dropshadow
> #549 Cards component zonder dropshadow mogelijk maken

- CHANGELOG.md
- docs/11-pdf-bestanden.md
Pdf-bestanden documentatie toegevoegd.
> #550 pdf documentatie

- src/styles/components/_shopping-cart.scss
- margin-top op dso-edit-additive gezet van 8px
- font-weight 400 voor dso-edit-additive
> #425 - Shopping cart uitbreiding

- CHANGELOG.md
- components/Componenten/accordion/accordion.config.yml
- components/Componenten/accordion/accordion.njk
- reference/render/aanvragen-file-upload.html
- reference/render/aanvragen.html
- reference/render/accordion--compact-met-links.html
- reference/render/accordion--default-met-links.html
- reference/render/accordion--default.html
- reference/render/accordion.html
- reference/render/checken.html
- src/styles/components/_accordion.scss
* Cherry-picked everything (from https://github.com/dso-toolkit/dso-toolkit/pull/597)
> #482 : Accordion: aria-expanded knoppen en/of links

- components/Componenten/accordion/accordion.config.yml
Er is een issue dat ik niet opgelost krijgt en dat is de link in Component in context. Die moet leiden naar een template pagina. Maar ik krijg dat niet voor mekaar. 
Suggesties?
> Documentatie aanpassing

- CHANGELOG.md
- components/Componenten/form-elements/group-select.njk
- reference/render/group-select--input-select-invalid.html
- reference/render/group-select--input-select-multiple.html
- reference/render/group-select--input-select-valid.html
- reference/render/group-select.html
- bij aanwezigheid helpText, dan aria-describedby op select
> #711 - Group select: aria-describedby gebruiken

- CHANGELOG.md
- docs/10-index.md
- docs/20-Fundament/11-pdf-bestanden.md
Simpele aanpassing url's aangepast naar nieuwe locaties op digitoegankelijkheid.nl
> #799 links bestaan niet meer

- CHANGELOG.md
- components/Componenten/icon/icon.config.js
> Iconen documentatie update

- CHANGELOG.md
- components/Componenten/attachments-counter/attachments-counter.config.yml
- components/Componenten/badge/badge.config.js
- components/Componenten/breadcrumbs/breadcrumbs.config.yml
Attachment counter, badge en breadcrumbs
> Documentatie update

- CHANGELOG.md
- packages/dso-toolkit/theme/views/partials/navigation/navigation.nunj
* h3 om button ipv h3 in button
> #992 Navigatie van Toolkit aanpassen aan gewijzigde treeview markup

- CHANGELOG.md
- packages/dso-toolkit/docs/20-Fundament/15-inline-validatie.md
Documentatie aanpassingen voor veld-validatie.
> #1018 Documentatie inline validatie geüpdatet

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_form.scss
---
Actie voor developer: Als het nodig is dat ... (`dso-justify-form-groups`)
- (voorbeeld URL invoegen)
@PieterVerheij straks bovenstaande compleet maken
> #1046 : Horizontale plaatsing form-groups en dso-form-buttons

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_breadcrumbs.scss
Geen breaking change
-----
Oude situatie:
https://dso-toolkit.nl/21.1.0/components/detail/breadcrumbs.html
https://dso-toolkit.nl/_1023.Breadcrumbs-aanpassingen/components/detail/breadcrumbs.html
> #1023.Breadcrumbs-aanpassingen

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/highlight-box/highlight-box.config.yml
* titels toegevoegd aan voorbeelden
> #1048 Op highlight box pagina hebben alle voorbeelden titel "Default"

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_breadcrumbs.scss
Nieuw PR, vanwege aanpassings wens. Oorspronkelijk PR: https://github.com/dso-toolkit/dso-toolkit/issues/1023
> #1023.breadcrumbs aanpassingen

- CHANGELOG.md
- packages/dso-toolkit/components/Voorbeelden/layout/layout.config.yml
- packages/dso-toolkit/components/Voorbeelden/layout/layout.njk
- packages/dso-toolkit/docs/20-Fundament/04-layout.md
- packages/dso-toolkit/reference/render/layout.html
> #977 Uitleg gebruik classes cols en rows

- CHANGELOG.md
- packages/styling/components/alert.scss
- packages/styling/variables/media-queries-breakpoints.scss
Geen breaking change
-----
Oude situatie:
https://dso-toolkit.nl/21.2.0/components/preview/alert.html
https://dso-toolkit.nl/_1064.Alert-Responsive/components/preview/alert.html
> #1064.Alert Responsive

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_tabs.scss
Visited state in tab is gewoon grijs ipv paars.
> #1073 : Visited state in Tabs verwijderen

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/dropdown-button/dropdown-button.config.js
Instructie voor implementatie uitgebreid.
> #875 Dropdown is niet met pijltjes te navigeren. 

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/banner/banner.njk
- packages/dso-toolkit/reference/render/banner--banner-with-headings.html
- packages/dso-toolkit/reference/render/banner--default.html
- packages/dso-toolkit/reference/render/banner--rich-content.html
- packages/dso-toolkit/reference/render/banner--warning.html
- packages/dso-toolkit/reference/render/pagina-met-banner.html
- packages/dso-toolkit/src/styles/components/_rich-content.scss
- packages/dso-toolkit/src/styles/mixins/_typography.scss
- packages/styling/components/banner.scss
_Geen_
-----
Oude situatie:
https://dso-toolkit.nl/21.3.0/components/detail/banner.html
https://dso-toolkit.nl/_768.Banner-responsive/components/detail/banner.html
> #768.Banner-responsive

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_form.scss
Geen
-----
De wijzigingen zijn het beste te bekijken in Percy: https://percy.io/dso-toolkit/dso-toolkit/builds/10152396?utm_campaign=dso-toolkit&utm_content=dso-toolkit&utm_source=github_status_public
> #1091.Verticale (onder)marge van form-groups

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/accordion/accordion.config.yml
- packages/dso-toolkit/reference/render/accordion--default-met-formulier.html
Geen
-----
Alle id's in de `accordion.config.yml` zijn uniek aan elkaar gemaakt.
> 1118.Accordion voorbeeld pagina bevat invalide HTML

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_search-bar.scss
> #1092.Verticale (onder)marge van dso-search-bar

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_breadcrumbs.scss
Geen
-----
Oude situatie:
https://dso-toolkit.nl/24.0.0/components/detail/breadcrumbs.html
https://dso-toolkit.nl/_1133.Breadcrumb-Slashes/components/detail/breadcrumbs.html
> #1133.Breadcrumb-Slashes

- CHANGELOG.md
- packages/css/stories/description/description.stories.ts
- packages/css/stories/description/readme.md
- packages/dso-toolkit/src/styles/dso.scss
- packages/dso-toolkit/src/styles/mixins/_dso-variables.scss
- packages/stories/src/index.ts
- packages/stories/src/stories/description.ts
- packages/styling/components.scss
- packages/styling/components/description.scss
> #1109.storybook html description

- CHANGELOG.md
- packages/css/src/components/breadcrumbs/breadcrumbs.template.ts
- packages/dso-toolkit/components/Componenten/breadcrumbs/breadcrumbs.njk
- packages/dso-toolkit/reference/render/404pagina.html
- packages/dso-toolkit/reference/render/beheer-basis.html
- packages/dso-toolkit/reference/render/breadcrumbs.html
- packages/dso-toolkit/reference/render/header.html
- packages/dso-toolkit/reference/render/landingspagina.html
- packages/dso-toolkit/reference/render/pagina-met-banner.html
- packages/dso-toolkit/reference/render/row-equal-heights.html
Geen
-----
**Oude situatie:**
https://dso-toolkit.nl/24.2.2/components/detail/breadcrumbs.html
**Nieuwe situatie:**
https://dso-toolkit.nl/_1157.Breadcrumb-validatiefout-voorbeeldpagina/components/detail/breadcrumbs.html
> #1157.Breadcrumb-validatiefout-voorbeeldpagina

- CHANGELOG.md
- packages/dso-toolkit/components/Voorbeelden/20-Toepassingen/10-Aanvragen/activiteiten.config.yml
- packages/dso-toolkit/reference/render/activiteiten.html
- packages/dso-toolkit/src/styles/components/_list-button.scss
Geen
-----
Oude situatie:
https://dso-toolkit.nl/24.2.2/components/detail/list-button.html
https://dso-toolkit.nl/24.2.2/components/detail/activiteiten.html
https://dso-toolkit.nl/_1161.ListButton-met-InputNumber-in-lijst-krijgt-geen-margin-top/components/detail/list-button.html
https://dso-toolkit.nl/_1161.ListButton-met-InputNumber-in-lijst-krijgt-geen-margin-top/components/detail/activiteiten.html
> #1161.ListButton met InputNumber in lijst krijgt geen margin-top

- CHANGELOG.md
- packages/sources/src/styling/mixins/rich-content.scss
> #1180.Afbeeldingen in table schalen niet goed

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/modal/modal.njk
- packages/dso-toolkit/reference/render/modal.html
- packages/dso-toolkit/src/styles/components/_button.scss
- packages/dso-toolkit/src/styles/components/_modal.scss
> #1177.Banner plus Modal responsive Bug

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/anchor/anchor.njk
- packages/dso-toolkit/reference/render/anchor--extern.html
- packages/dso-toolkit/reference/render/anchors.html
- packages/dso-toolkit/reference/render/buttons.html
- packages/dso-toolkit/reference/render/full-width.html
- packages/dso-toolkit/reference/render/rich-content.html
> #1176.anchor tekst externe link

- packages/css/src/components/anchor/anchor.stories.ts
- packages/css/src/components/anchor/anchor.template.ts
- packages/css/src/components/anchor/readme.md
- packages/css/src/components/banner/banner.stories.ts
- packages/css/src/components/button/button.template.ts
- packages/css/src/components/highlight-box/highlight-box.stories.ts
- packages/css/src/components/info/info.stories.ts
- packages/css/src/components/link-list/link-list.template.ts
- packages/sources/src/components/anchor/anchor.args.ts
- packages/sources/src/components/anchor/anchor.models.ts
- packages/sources/src/components/anchor/anchor.stories.ts
- packages/sources/src/components/button/button.args.ts
- packages/sources/src/components/button/button.models.ts
- packages/sources/src/components/button/button.stories.ts
- packages/sources/src/index.ts
> #862.storybook css component anchor

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/list-button/list-button.config.yml
- packages/dso-toolkit/components/Voorbeelden/20-Toepassingen/10-Aanvragen/activiteiten.config.yml
- packages/dso-toolkit/components/Voorbeelden/20-Toepassingen/10-Aanvragen/documenten.config.yml
- packages/dso-toolkit/reference/render/activiteiten.html
- packages/dso-toolkit/reference/render/documenten.html
- packages/dso-toolkit/reference/render/list-button--button-met-extra-label-en-input-number.html
- packages/dso-toolkit/reference/render/list-button--button-met-input-number-selected.html
- packages/dso-toolkit/reference/render/list-button--button-met-input-number.html
- packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst-en-extra-label.html
- packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst-en-input-number-en-extra-label.html
- packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst-en-input-number.html
- packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst.html
- packages/dso-toolkit/reference/render/list-button--button-met-optionele-tekst-en-input-number-en-extra-label.html
- packages/dso-toolkit/reference/render/list-button--button-met-optionele-tekst-en-input-number.html
Geen
-----
**Oude situatie:**
https://dso-toolkit.nl/25.1.2/components/detail/list-button.html
https://dso-toolkit.nl/25.1.2/components/detail/documenten.html
https://dso-toolkit.nl/25.1.2/components/detail/activiteiten.html
**Nieuwe situatie:**
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/list-button.html
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/documenten.html
https://dso-toolkit.nl/_1220.lege-spans-en-ids-in-toolkit/components/detail/activiteiten.html
> #1220.lege spans en ids in toolkit

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/form-elements/group-files.njk
- packages/dso-toolkit/reference/render/documenten.html
- packages/dso-toolkit/reference/render/form--form-horizontal.html
- packages/dso-toolkit/reference/render/form--form-vertical.html
- packages/dso-toolkit/reference/render/group-files--default.html
- packages/dso-toolkit/reference/render/group-files--input-file-confidential.html
- packages/dso-toolkit/reference/render/group-files--input-file-description.html
- packages/dso-toolkit/reference/render/group-files--input-file-disabled.html
- packages/dso-toolkit/reference/render/group-files--input-file-explanation.html
- packages/dso-toolkit/reference/render/group-files--input-file-invalid.html
- packages/dso-toolkit/reference/render/group-files--input-file-required.html
- packages/dso-toolkit/reference/render/group-files--input-file-valid.html
- packages/dso-toolkit/reference/render/modal.html
- packages/dso-toolkit/reference/render/verzoeken-indienen.html
- packages/dso-toolkit/src/styles/components/form/_files.scss
- alle voorbeelden van deze deprecated werkvorm verwijderd
- styling verwijderd
> #1243.Group-Files-deprecated-class-dso-description-verwijderen

- CHANGELOG.md
- packages/css/src/components/search-bar/search-bar.scss
- packages/css/src/dso.scss
- packages/dso-toolkit/src/styles/components/_search-bar.scss
#1318 Fixed: Autosuggest in Search Bar zorgt ervoor dat Search Bar elementen verkeerd uitlijnen
> #1316 Search Bar styling naar @dso-toolkit/css

- CHANGELOG.md
- packages/dso-toolkit/src/styles/components/_shopping-cart.scss
- packages/sources/src/components/highlight-box/highlight-box.scss
- packages/sources/src/components/info/info.scss
- packages/sources/src/icons/times.scss
- packages/sources/src/styling/global/footer.scss
- packages/sources/src/styling/global/table.scss
Test url's
**Oud:**
https://dso-toolkit.nl/master/components/detail/shopping-cart.html
https://dso-toolkit.nl/master/components/detail/table.html
https://dso-toolkit.nl/master/components/detail/highlight-box.html
https://dso-toolkit.nl/master/components/detail/info.html
https://dso-toolkit.nl/master/components/detail/footer.html
**Nieuw:**
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/shopping-cart.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/table.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/highlight-box.html
https://dso-toolkit.nl/_1363.Standaard-grijs-5-als-grijze-achtergrond/components/detail/info.html …
> #1363.Standaard $grijs-5 als grijze achtergrond

- CHANGELOG.md
- packages/dso-toolkit/components/Voorbeelden/20-Toepassingen/30-Vergunningcheck/resultaat.njk
- packages/dso-toolkit/reference/render/resultaat.html
Kleine aanpassing voor de vergunningcheck resultaat pagina
> #1430 Voorbeeldpagina conclusie Vergunningcheck aanpassen 'Opslaan in Mijn Omgevingswet'

- CHANGELOG.md
- cypress/integration/core/date-picker.spec.ts
- packages/core/src/components/date-picker/date-picker.tsx
- fix: geen fout bij datum buiten opgegeven range
- fix: geen fout bij niet toegestane karakters
- fix: niet toegestane karakters blokkeren
> #1482 Date Picker betere foutafhandeling

- CHANGELOG.md
- packages/core/src/components/date-picker/readme.md
- packages/dso-toolkit/components/Componenten/alert/alert.config.yml
- packages/dso-toolkit/components/Componenten/banner/banner.config.yml
- packages/dso-toolkit/components/Componenten/breadcrumbs/breadcrumbs.config.yml
- packages/dso-toolkit/components/Componenten/date-picker/date-picker.config.yml
- packages/dso-toolkit/components/Componenten/label-css/label-css.config.js
- packages/dso-toolkit/components/Componenten/progress-bar/progress-bar.config.yml
- packages/dso-toolkit/components/Componenten/table/table.config.yml
- packages/dso-toolkit/docs/20-Fundament/14-meldingenstrategie.md
- packages/dso-toolkit/docs/20-Fundament/16-pagina-titels.md
Pullrequest met de volgende wijzigingen. 
Added
Fundament documentatie omtrent Pagina titels
Changed: 
Datepicker Documentatie
Label Documentatie
> #1469 Documentatie Label, Datepicker en paginatitel update

- CHANGELOG.md
- packages/dso-toolkit/components/Componenten/_whitebox-regular/whitebox-regular.njk
- packages/dso-toolkit/components/Componenten/tile/tile.njk
- packages/dso-toolkit/reference/render/homepage.html
- packages/dso-toolkit/reference/render/row-equal-heights.html
- packages/dso-toolkit/reference/render/tile.html
- packages/dso-toolkit/reference/render/whitebox-regular--default.html
- packages/dso-toolkit/reference/render/whitebox-regular--whitebox-counter.html
- packages/dso-toolkit/reference/render/whitebox-regular--whitebox-icon.html
- packages/dso-toolkit/reference/render/whitebox.html
Whitebox en Tiles aanpassingen met betrekking tot alt text
> #1540 whitebox invalid html door imgtag zonder alt

- CHANGELOG.md
- packages/core/src/components/selectable/selectable.tsx
- packages/css/src/components/form/form-groups/checkboxes/form-group-checkboxes.template.ts
- packages/css/src/components/form/form-groups/radios/form-group-radios.template.ts
- packages/css/src/components/info/info.template.ts
- packages/css/src/components/selectable/selectable.template.ts
-describedBy fixes voor radios en checkbos
-id op dso-info
> #1399 dso-info fixes voor selectables

- CHANGELOG.md
- cypress/integration/core/autosuggest.spec.ts
- packages/core/src/components.d.ts
- packages/core/src/components/autosuggest/autosuggest.stories.ts
- packages/core/src/components/autosuggest/autosuggest.template.ts
- packages/core/src/components/autosuggest/autosuggest.tsx
- packages/react/src/components/autosuggest/autosuggest.stories.tsx
- packages/react/src/components/autosuggest/autosuggest.template.tsx
- packages/sources/src/components/autosuggest/autosuggest.args.ts
- packages/sources/src/components/autosuggest/autosuggest.models.ts
- packages/sources/src/components/autosuggest/autosuggest.stories.ts
Property `loadingDelayed` toegevoegd om vertraging van het tonen van de progress indicator te kunnen configureren.
> #1625 Autosuggest vertraging op loading state

- CHANGELOG.md
- cypress/integration/core/toggletip.spec.ts
- packages/core/src/components.d.ts
- packages/core/src/components/info-button/info-button.tsx
- packages/core/src/components/info-button/readme.md
- packages/core/src/components/toggletip/toggletip.tsx
Selecteren van het button element uit de ComponentDidRender gehaald en gelegd bij `dso-info-button`.
> #1670 DsoToggletip: Error: button not found

- CHANGELOG.md
- cypress/integration/helpcenter-panel.spec.ts
- packages/core/src/components/helpcenter-panel/helpcenter-panel.tsx
* panel sluiten op escape.
* scrollen niet mogelijk wanneer panel open is.
* focus trap op open panel
> #1770 Helpcenterpanel - stop background scroll and trap focus

- CHANGELOG.md
- cypress/integration/helpcenter-panel.spec.ts
- packages/core/src/components/helpcenter-panel/helpcenter-panel.scss
- 480px en kleiner = 320px
- tot 768px = 480px
- vanaf 768px = 640px
> #1781 Helpcenterpanel - Responsive maken

- CHANGELOG.md
- cypress/integration/ozon-content.spec.ts
- packages/core/src/components/ozon-content/nodes/lijst.node.tsx
- packages/core/src/components/ozon-content/ozon-content-mapper.tsx
- packages/core/src/components/ozon-content/ozon-content.scss
- packages/sources/src/components/ozon-content/ozon-content.content.ts
- Ozon content `Lijst` node
- stijling voor: 
- expliciete en ongemarkeerde lijsten
- geneste lijsten (ook mix tussen expliciet en ongemarkeerd)
> #1792 Ozon content lijst node

- storybook/src/example-pages/componenten/Typografie.ts
- website/docs/fundament/typografie.mdx
- Storybook-pagina toegevoegd
- In documentatie Storybook-pagina toevoegen.
> Typografie toevoeging

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/map-controls/map-controls.interfaces.ts
- packages/core/src/components/map-controls/map-controls.tsx
- packages/core/src/components/map-controls/readme.md
- packages/core/src/index.ts
- packages/dso-toolkit/src/components/map-controls/map-controls.args.ts
- packages/dso-toolkit/src/components/map-controls/map-controls.models.ts
- storybook/cypress/e2e/map-controls.cy.ts
- storybook/src/components/map-controls/map-controls.core-template.ts
Als Kaartlagen panel in- en uitgeklapt wordt
> #2033 Extra event vanuit Map control component

- CHANGELOG.md
- packages/core/src/components/accordion/components/accordion-section-theme-conclusion.scss
- packages/dso-toolkit/src/components/accordion/accordion-theme-conclusion.scss
- packages/dso-toolkit/src/components/accordion/accordion.variables.scss
- packages/dso-toolkit/src/components/alert/alert.mixins.scss
- packages/dso-toolkit/src/components/badge/badge.mixins.scss
- packages/dso-toolkit/src/components/banner/banner.mixins.scss
- packages/dso-toolkit/src/components/banner/banner.stories-of.ts
- packages/dso-toolkit/src/components/document-header/document-header.scss
- packages/dso-toolkit/src/components/document-list/document-list.scss
- packages/dso-toolkit/src/components/footer/footer.scss
- packages/dso-toolkit/src/components/grid/grid.scss
- packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
- packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
- packages/dso-toolkit/src/components/info/info.mixins.scss
- packages/dso-toolkit/src/components/info/info.scss
- packages/dso-toolkit/src/components/label/label.variables.scss
- packages/dso-toolkit/src/components/link-list/link-list.mixins.scss
- packages/dso-toolkit/src/components/shopping-cart/shopping-cart.scss
- packages/dso-toolkit/src/icons/chevron-down.scss
- packages/dso-toolkit/src/icons/chevron-right.scss
- packages/dso-toolkit/src/icons/chevron-up.scss
- packages/dso-toolkit/src/icons/download.scss
- packages/dso-toolkit/src/icons/external-link.scss
- packages/dso-toolkit/src/icons/paperclip.scss
- packages/dso-toolkit/src/variables/states.scss
op gekleurde achtergrond naar #000
> #2005 Tekstkleur tekst en interactieve element

- CHANGELOG.md
- angular-workspace/components/selectable/selectable.angular-template.ts
- packages/core/src/components.d.ts
- packages/core/src/components/selectable/readme.md
- packages/core/src/components/selectable/selectable.scss
- packages/core/src/components/selectable/selectable.tsx
- packages/dso-toolkit/src/components/button/button.models.ts
- packages/dso-toolkit/src/components/card/card.args.ts
- packages/dso-toolkit/src/components/card/card.content.ts
- packages/dso-toolkit/src/components/selectable/selectable.models.ts
- packages/react/src/components/card/card.react-template.tsx
- packages/react/src/components/selectable/selectable.react-template.tsx
- storybook/src/components/button/button.css-template.ts
- storybook/src/components/card/card.core-template.ts
- storybook/src/components/card/card.css-template.ts
- storybook/src/components/selectable/selectable.core-template.ts
- storybook/src/components/selectable/selectable.css-template.ts
Titel in labels selectievakje en informatie knopje
> #2006 card -  selectable: titel in toegankelijke naam

- CHANGELOG.md
- packages/core/src/components/selectable/selectable.scss
- packages/dso-toolkit/src/components/selectable/selectable.scss
+ fix info stijling (kapot sinds [#1845](https://github.com/dso-toolkit/dso-toolkit/issues/1845))
> #2037 Rode border op invalid Selectable

- CHANGELOG.md
- packages/dso-toolkit/src/components/action-list/action-list.scss
- packages/dso-toolkit/src/components/form/content/checkboxes.content.ts
- packages/dso-toolkit/src/components/form/content/input.content.ts
- packages/dso-toolkit/src/components/form/content/radios.content.ts
- packages/dso-toolkit/src/components/form/content/search-bar.content.ts
- packages/dso-toolkit/src/components/form/content/select.content.ts
- packages/dso-toolkit/src/components/form/content/static.content.ts
- packages/dso-toolkit/src/components/form/content/textarea.content.ts
- packages/dso-toolkit/src/components/form/form-group.scss
- packages/dso-toolkit/src/components/headings/headings.mixins.scss
* Rich Content in Action List Item
* Info in Form
> #2110 h5 zonder marges

- CHANGELOG.md
- packages/core/src/components/autosuggest/autosuggest.tsx
aria-live: "polite" toevoegen aan autosuggest component.
> #2267 [Added] Autosuggest: niet gevonden melding en eerste suggestie voorlezen.

- CHANGELOG.md
- packages/dso-toolkit/src/components/accordion/accordion-theme-compact.scss
Styles werden overschreven; selectors omgedraaid.
> #2343 accordion compact reverse align werkt niet

- CHANGELOG.md
- packages/dso-toolkit/src/components/form/form-group.scss
@MYpenburg special request
Get this into #2217
> #2357 [Fixed] Form-group: top spacing after image list

- CHANGELOG.md
- packages/dso-toolkit/src/components/card/card.scss
- packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
- packages/dso-toolkit/src/components/image/image.scss
- packages/dso-toolkit/src/components/viewer-grid/viewer-grid.scss
General max-inline-size set to 100%
> #2401 [Fixed] Image: Large image overflows container

- CHANGELOG.md
- packages/core/src/components/highlight-box/highlight-box.scss
- packages/dso-toolkit/src/components/highlight-box/highlight-box.scss
> #2427 [Fixed] Highlight box: Stacking issue

- CHANGELOG.md
- packages/dso-toolkit/src/global/spacing.scss
- storybook/src/components/form/form-group-input.css-template.ts
- storybook/src/components/form/form-group-select.css-template.ts
- storybook/src/components/form/form-group-textarea.css-template.ts
add temp spacing rule in spacing.scss
> #2440 [Fixed] Button row: Verticale ruimte ontbreekt

- CHANGELOG.md
- packages/core/src/components/logo/logo.tsx
- storybook/cypress/e2e/logo.cy.ts
- storybook/src/components/logo/logo.core-template.ts
> #2489 [Fixed] Logo: Responsiveness stuk

- CHANGELOG.md
- packages/dso-toolkit/src/components/modal/modal.mixins.scss
tijd naar 200ms, animatienaam aangepast aan de werkelijkheid (bijvangst)
> #2463 [Changed] Modal: Fade in animatietijd naar 200ms

- CHANGELOG.md
- packages/dso-toolkit/src/components/form/form-buttons/form-buttons.scss
- packages/dso-toolkit/src/variables/media-query-breakpoints.scss
float to flexbox, together with all the trimmings :)
form buttons now stacking on small viewport (=< 480px)
> #2464 form buttons responsive behavior

- CHANGELOG.md
- packages/dso-toolkit/src/components/form/form-explanation.scss
- packages/dso-toolkit/src/components/form/form.args.ts
- packages/dso-toolkit/src/components/form/form.mixins.scss
- packages/dso-toolkit/src/components/form/form.models.ts
- packages/dso-toolkit/src/components/form/form.scss
- packages/dso-toolkit/src/components/form/models/form.model.ts
- packages/dso-toolkit/src/index.ts
- storybook/src/components/form/form.css-template.ts
> #2453 form explanation required field

- CHANGELOG.md
- packages/dso-toolkit/src/components/grid/grid.scss
- storybook/src/example-pages/toepassingen/loket/homepage.ts
Non-breaking change, CSS only.
Tested in 4 major browsers (latest stable versions)
> #2414 [Changed] Banner: Responsive behavior

- CHANGELOG.md
- packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
New improved responsive behavior using existing media query
> #2532 [Added] Form: File responsive behavior

- CHANGELOG.md
- packages/dso-toolkit/src/components/action-list/action-list.scss
Added margin to rich content if it follows an action list item
> #2544 [Fixed] Action List: Rich content align

- CHANGELOG.md
- packages/core/src/components/scrollable/scrollable.scss
> #2526 [Fixed] Map Layers: Scroll overlay stacking

- CHANGELOG.md
- packages/dso-toolkit/src/components/grid/grid.scss
Checked result with UX (@MichielDHVD
> #2685 [Fixed] Banner: Fix background color

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/icon/readme.md
- packages/core/src/components/panel/panel.scss
- packages/core/src/components/panel/panel.tsx
- packages/core/src/components/panel/readme.md
- packages/dso-toolkit/src/components/panel/index.ts
- packages/dso-toolkit/src/components/panel/panel.args.ts
- packages/dso-toolkit/src/components/panel/panel.models.ts
- packages/dso-toolkit/src/components/panel/panel.stories-of.ts
- packages/dso-toolkit/src/index.ts
- storybook/cypress/e2e/panel.cy.ts
- storybook/src/components/panel/panel.core-stories.ts
- storybook/src/components/panel/panel.core-template.ts
- storybook/src/templates.ts
Ik hoor graag wat hier nog ontbreekt.
> #2711 Panel: New component

- .gitignore
- CHANGELOG.md
- deploy.sh
- scripts/create-hashes/index.ts
- website/docs/voor-developers/api.mdx
Package @dso-toolkit/core: https://cdn.dso-toolkit.nl/@dso-toolkit/core/_2688-Build--Artifact-integrity/hashes.json
Package dso-toolkit: https://cdn.dso-toolkit.nl/dso-toolkit/_2688-Build--Artifact-integrity/hashes.json
> #2688 [Added] Build: Artifact integrity

- CHANGELOG.md
- packages/dso-toolkit/src/global/spacing.scss
- storybook/src/example-pages/toepassingen/aanvragen/activiteiten.ts
Needs testing on the issue itself
> #2800 [Docs] Button row: No block margin

- CHANGELOG.md
- packages/core/src/components/viewer-grid/viewer-grid.scss
- storybook/cypress/e2e/viewer-grid.cy.ts
enclosed props block in & {...}
> #2822 [Fixed] Viewer Grid: Button styling broken

- CHANGELOG.md
- packages/core/src/components/helpcenter-panel/helpcenter-panel.scss
- packages/core/src/components/image-overlay/image-overlay.scss
- packages/core/src/components/legend-item/legend-item.scss
- packages/core/src/components/list-button/list-button.scss
- packages/core/src/components/map-controls/map-controls.scss
- packages/core/src/components/viewer-grid/viewer-grid.scss
- packages/dso-toolkit/src/components/button/button.mixins.scss
- storybook/cypress/e2e/map-controls.cy.ts
> #2794 [Fixed] Map Controls: Button styling broken

- CHANGELOG.md
- packages/dso-toolkit/src/components/dropdown-menu/dropdown-menu.scss
hover state removed, active state added.
> #2851 [Fixed] Dropdown menu: Button icon hover color

- CHANGELOG.md
- packages/dso-toolkit/src/components/banner/banner.mixins.scss
- packages/dso-toolkit/src/components/banner/banner.scss
- packages/dso-toolkit/src/components/banner/banner.variables.scss
- storybook/src/components/banner/banner.core-template.ts
- storybook/src/components/banner/banner.css-template.ts
- website/blog/2024-12-16-dso-toolkit-67.2.0.mdx
Whats new:
- HTML: `container` and `row` divs deleted, `col-` div renamed to `dso-banner-inner`.
- CSS: styling adjusted to the above markup changes.
> #2303 [Changed] Banner: No dependency on grid system

- CHANGELOG.md
- website/docs/voor-maintainers/refinement-estimates.md
> #2893 Docs: Handvat voor refinement estimates publiceren

- CHANGELOG.md
- packages/core/src/components/icon/icon.tsx
- packages/dso-toolkit/src/icons/mail.scss
- packages/dso-toolkit/src/icons/mail.svg
> #2918 [Added] Icon: Mail

- CHANGELOG.md
- angular-workspace/components/alert/alert.angular-template.ts
- packages/core/src/components.d.ts
- packages/core/src/components/alert/alert.i18n.ts
- packages/core/src/components/alert/alert.interfaces.ts
- packages/core/src/components/alert/alert.scss
- packages/core/src/components/alert/alert.tsx
- packages/core/src/components/alert/readme.md
- packages/dso-toolkit/src/components/alert/alert.args.ts
- packages/dso-toolkit/src/components/alert/alert.mixins.scss
- packages/dso-toolkit/src/components/alert/alert.models.ts
- packages/dso-toolkit/src/components/alert/alert.scss
- packages/dso-toolkit/src/components/alert/alert.stories-of.ts
- packages/react/src/components/alert/alert.react-template.tsx
- storybook/cypress/e2e/alert.cy.ts
- storybook/src/components/alert/alert.core-template.ts
- storybook/src/components/alert/alert.css-template.ts
> #2745 [Added] Alert: Nieuwe optie "closable"

- CHANGELOG.md
- angular-workspace/components/list-button/list-button.angular-template.ts
- angular-workspace/components/list-button/list-button.stories.ts
- package.json
- packages/core/src/components.d.ts
- packages/core/src/components/list-button/list-button.scss
- packages/core/src/components/list-button/list-button.tsx
- packages/core/src/components/list-button/list-button.variables.scss
- packages/core/src/components/list-button/readme.md
- packages/dso-toolkit/src/components/list-button/list-button.args.ts
- packages/dso-toolkit/src/components/list-button/list-button.models.ts
- packages/dso-toolkit/src/components/list-button/list-button.stories-of.ts
- packages/react/src/components/list-button/list-button.react-template.tsx
- packages/react/src/components/list-button/list-button.stories.tsx
- storybook/cypress/e2e/list-button.cy.ts
- storybook/cypress/fixtures/image-snapshot-components.json
- storybook/src/components/list-button/list-button.core-stories.ts
- storybook/src/components/list-button/list-button.core-template.ts
- website/blog/2024-11-25-dso-toolkit-67.0.0.mdx
- website/blog/2024-12-19-dso-toolkit-67.2.0.mdx
- website/blog/2025-01-20-dso-toolkit-68.0.0.mdx
> #2555 List Button: Het wijzigen van het aantal met plus/min knoppen is ontoegankelijk

- CHANGELOG.md
- packages/dso-toolkit/src/components/modal/modal.stories-of.ts
- packages/react/src/components/modal/modal.react-template.tsx
> #2961 [Fixed] Modal: Angular modal toont geen sluitkruisje in storybook

- CHANGELOG.md
- storybook/cypress/e2e/autosuggest.cy.ts
> #2984 [Fixed] Autosuggest: incorrecte matchImageSnapshot in baseline

- packages/core/src/components/card-container/readme.md
- packages/core/src/components/map-controls/readme.md
- storybook/src/components/info/info.core-stories.ts
- storybook/src/components/rich-content/rich-content.css-stories.ts
- storybook/src/components/tile-grid/tile-grid.css-stories.ts
- website/docs/components/form/form-buttons.mdx
- website/docs/components/form/justify-form-groups.mdx
- website/docs/components/form/search-bar.mdx
Deze PR beavt een aantal correcties op voorgaande omzettingen van `storiesOf()` naar CSF.
> #2316 [Task] Storybook: `storiesOf()` naar CSF

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/panel/panel.scss
- packages/core/src/components/panel/panel.tsx
- packages/core/src/components/panel/panel.variables.scss
- packages/core/src/components/panel/readme.md
- packages/dso-toolkit/src/components/panel/panel.args.ts
- packages/dso-toolkit/src/components/panel/panel.models.ts
- packages/dso-toolkit/src/components/panel/panel.stories-of.ts
- storybook/cypress/e2e/panel.cy.ts
- storybook/src/components/panel/panel.core-stories.ts
- storybook/src/components/panel/panel.core-template.ts
> #2978 [Added] Panel: Optie "emphasized"

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/accordion/accordion.interfaces.ts
- packages/core/src/components/accordion/accordion.tsx
- packages/core/src/components/accordion/readme.md
- packages/dso-toolkit/src/components/accordion/accordion.args.ts
- packages/dso-toolkit/src/components/accordion/accordion.stories-of.ts
- storybook/src/components/accordion/accordion.core-template.ts
> #2957 [Fixed] Accordion: Styling van React implementatie niet gelijk aan Core en HTML/CSS componenten

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/panel/panel.scss
- packages/core/src/components/panel/panel.variables.scss
- packages/core/src/components/panel/readme.md
- packages/core/src/components/survey-rating/readme.md
- packages/core/src/components/survey-rating/survey-rating.interfaces.ts
- packages/core/src/components/survey-rating/survey-rating.scss
- packages/core/src/components/survey-rating/survey-rating.tsx
- packages/core/src/components/survey-rating/survey-rating.variables.scss
- packages/dso-toolkit/src/components/survey-rating/index.ts
- packages/dso-toolkit/src/components/survey-rating/survey-rating.args.ts
- packages/dso-toolkit/src/components/survey-rating/survey-rating.models.ts
- packages/dso-toolkit/src/components/survey-rating/survey-rating.stories-of.ts
- packages/dso-toolkit/src/index.ts
- storybook/cypress/e2e/survey-rating.cy.ts
- storybook/src/components/survey-rating/survey-rating.core-stories.ts
- storybook/src/components/survey-rating/survey-rating.core-template.ts
- storybook/src/templates.ts
==> De falende e2e test is vanwege 2 nieuwe screenshots.
> #2603 [Added] Survey Rating: Nieuw component

- CHANGELOG.md
- packages/core/src/components/list-button/list-button.scss
- packages/core/src/components/list-button/list-button.variables.scss
- packages/dso-toolkit/src/global/spacing.scss
Ook pas mergen na akkoord @MYpenburg. Zie ook: https://github.com/dso-toolkit/dso-toolkit/issues/3008#issuecomment-2666267369
> #3008 [Fixed] Verticaal Ritme: List Buttons staan tegen elkaar aan geplakt

- CHANGELOG.md
- packages/core/src/components/accordion/components/accordion-section-theme-default.scss
- packages/core/src/components/accordion/components/accordion-section.scss
> #3009 [Fixed] Accordion: Default variant tussenruimte secties is niet consistent

- CHANGELOG.md
- storybook/src/components/pagination/pagination.css-stories.ts
- storybook/src/components/pagination/pagination.css-template.ts
> #2867 pagination deprecate html css component

- CHANGELOG.md
- packages/core/src/components/annotation/annotation-activiteit/annotation-activiteit.tsx
- packages/core/src/components/annotation/annotation-list-renvooi-values.tsx
- packages/core/src/components/annotation/annotation-omgevingsnormwaarde/annotation-omgevingsnormwaarde.tsx
- packages/core/src/components/renvooi/renvooi.tsx
- storybook/cypress/e2e/annotation.cy.ts
- website/blog/2025-01-20-dso-toolkit-69.0.0.mdx
> #2975 [Changed] Annotation & Renvooi: Presenteren van renvooi items als komma gescheiden lijst verplaatsen

- CHANGELOG.md
- angular-workspace/package.json
- package.json
- packages/core/package.json
- packages/dso-toolkit/package.json
- packages/react/package.json
- packages/react/src/components/expandable/expandable.decorator.tsx
- packages/react/src/components/label/label.decorator.tsx
- storybook/package.json
- website/package.json
- yarn.lock
> #2987 [Task] Packages: Typescript updaten naar `~5.7.3` of hoger

- CHANGELOG.md
- angular-workspace/components/pagination/pagination.stories.ts
- packages/core/src/components/pagination/pagination.tsx
- packages/dso-toolkit/src/components/pagination/pagination.args.ts
- packages/dso-toolkit/src/components/pagination/pagination.models.ts
- packages/dso-toolkit/src/components/pagination/pagination.stories-of.ts
- packages/react/src/components/pagination/pagination.stories.tsx
- storybook/cypress/e2e/pagination.cy.ts
- storybook/src/components/pagination/pagination.core-stories.ts
- storybook/src/components/pagination/pagination.core-template.ts
- storybook/src/components/pagination/pagination.css-template.ts
- website/blog/2025-02-28-dso-toolkit-68.6.0.mdx
- website/blog/authors.yml
**‼️ De E2E van pagination faalt op de snapshot omdat er nieuwe code in staat**
> #2875 [Changed] Pagination: maak totalPages optioneel

- CHANGELOG.md
- packages/core/src/components/scrollable/scrollable.tsx
> #3007 [Fixed] Autosuggest: TypeError reading `$instanceValues$` bij unmounten

- CHANGELOG.md
- packages/core/src/components/document-component/document-component.scss
> #3038 [Fixed] Document Component: Links zijn niet groen

- CHANGELOG.md
- packages/core/src/components/tooltip/tooltip.scss
> #3005 [Fixed] Tooltip: Ruimte tussen tooltip-arrow en tooltip-inner

- CHANGELOG.md
- packages/dso-toolkit/src/components/contact-information/contact-information.content.ts
- packages/dso-toolkit/src/components/contact-information/contact-information.stories-of.ts
- packages/dso-toolkit/src/global/spacing.scss
- packages/react/src/components/action-list/action-list.content.tsx
- storybook/src/components/action-list/action-list.content.ts
- storybook/src/components/action-list/action-list.core-template.ts
> #3012 [Added] Verticaal Ritme: aanpassing ruimte tussen contactinformatie blokken

- CHANGELOG.md
- storybook/cypress/e2e/action-list.cy.ts
> #2984 [Task] Action List: flaky screenshot test

- CHANGELOG.md
- storybook/cypress/e2e/dropdown-menu.cy.ts
> #3081 [Task] Dropdown Menu: Flaky tests fix

- CHANGELOG.md
- packages/dso-toolkit/src/components/banner/banner.mixins.scss
- packages/dso-toolkit/src/components/banner/banner.scss
- website/blog/2025-03-31-dso-toolkit-next.mdx
> #2930 [Changed] Banner: Legacy selector `.banner` verwijderen

- CHANGELOG.md
- storybook/cypress/e2e/image-snapshot-components.cy.ts
- storybook/cypress/e2e/ozon-content.cy.ts
- storybook/cypress/fixtures/image-snapshot-components.json
- storybook/cypress/support/commands.ts
> #2853 [Task] Ozon Content: onderzoek en fix flaky e2e test

- CHANGELOG.md
- angular-workspace/components/highlight-box/highlight-box.content.ts
- packages/dso-toolkit/src/components/anchor/anchor.variables.scss
- packages/dso-toolkit/src/components/button/button.mixins.scss
- packages/dso-toolkit/src/components/button/button.scss
- packages/dso-toolkit/src/components/highlight-box/highlight-box.mixins.scss
- packages/dso-toolkit/src/global/mixins/set-colors.mixin.scss
- packages/dso-toolkit/src/icons/external-link.scss
- packages/react/src/components/highlight-box/highlight-box.stories.tsx
- storybook/src/components/button/button.css-template.ts
- storybook/src/components/highlight-box/highlight-box.core-stories.ts
- storybook/src/components/highlight-box/highlight-box.css-stories.ts
In dit issue ook de volgende zaken gefixed: 
- Uitlijning van een icon only button
- Styling klopt niet van de primary button wanneer er gekozen werd voor een anchor element en mode extern aanstond. Zie [hier](https://storybook.dso-toolkit.nl/69.2.1/?path=/story/html-css-button--primary&args=element:anchor;variant:tertiary;mode:extern;truncate:!false;compact:!false)
- Extra etalering van buttons met mode in de highlight-box
> #3055 [Fixed] Button: Externe links in highlight box hebben herhalend icoon

- CHANGELOG.md
- website/docs/voor-maintainers/dependencies-update-procedure.md
> #3031 [Docs] Website: Typescript update procedure

- CHANGELOG.md
- packages/core/src/components/viewer-grid/viewer-grid.scss
> #3096 [Fixed] Viewer Grid: ScrollIntoView scrolled te ver door

- CHANGELOG.md
- packages/core/src/components/header/header.tsx
> #3100 [Fixed] Angular: Karma testrunner error in @stencil/core/internal/client/index.js

- CHANGELOG.md
- packages/core/src/components/autosuggest/autosuggest.tsx
> #3015 [Changed] Autosuggest: Aria-live van ul naar vaste div met .sr-only verplaatsen

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/document-component/document-component.tsx
- packages/core/src/components/ozon-content/nodes/kop.node.tsx
- packages/core/src/components/ozon-content/ozon-content-context.interface.ts
- packages/core/src/components/ozon-content/ozon-content-mapper.tsx
- packages/core/src/components/ozon-content/ozon-content.tsx
- packages/core/src/components/ozon-content/readme.md
- packages/dso-toolkit/src/components/document-component/document-component.args.ts
- packages/dso-toolkit/src/components/document-component/document-component.stories-of.ts
- storybook/cypress/e2e/document-component.cy.ts
- storybook/src/components/document-component/document-component.core-stories.ts
- website/blog/2025-03-31-dso-toolkit-70.0.0.mdx
- website/blog/2025-04-28-dso-toolkit-71.0.0.mdx
> #3110 [Fixed] Document Component: Kop werkt niet goed

- CHANGELOG.md
- packages/react/package.json
- website/blog/2025-05-12-dso-toolkit-72.0.0.mdx
- website/docs/voor-maintainers/refinement-estimates.md
- yarn.lock
> #3077 [Task] React: Update peerDependencies naar 19, verwijder 17

- CHANGELOG.md
- packages/core/src/components/autosuggest/autosuggest.scss
> #3060 [Changed] Autosuggest: Aanpassing top padding Suggestion Groups

- .prettierrc.json
- CHANGELOG.md
- package.json
- yarn.lock
> #3127 [Task] Prettier: gebruik prettier-config van `@infoprojects/prettier-config

- CHANGELOG.md
- storybook/cypress/fixtures/image-snapshot-voorbeeldpaginas.json
- storybook/src/example-pages/toepassingen/regels-op-de-kaart/documenten-VDK-zoeken.ts
- storybook/src/example-pages/toepassingen/regels-op-de-kaart/documenten-VDK.content.ts
> #3104 [Changed] Searchbar: Uitlijnen dropdown met titel invulveld

- CHANGELOG.md
- angular-workspace/components/action-list/action-list.stories.ts
- angular-workspace/components/alert/alert.stories.ts
- angular-workspace/components/attachments-counter/attachments-counter.stories.ts
- angular-workspace/components/badge/badge.stories.ts
- angular-workspace/components/date-picker-legacy/date-picker-legacy.stories.ts
- angular-workspace/components/date-picker/date-picker.stories.ts
- angular-workspace/components/dropdown-menu/dropdown-menu.stories.ts
- angular-workspace/components/expandable/expandable.stories.ts
- angular-workspace/components/header/header.stories.ts
- angular-workspace/components/highlight-box/highlight-box.stories.ts
- angular-workspace/components/icon/icon.stories.ts
- angular-workspace/components/image-overlay/image-overlay.stories.ts
- angular-workspace/components/info-button/info-button.stories.ts
- angular-workspace/components/info/info.stories.ts
- angular-workspace/components/list-button/list-button.stories.ts
- angular-workspace/components/modal/modal.stories.ts
- angular-workspace/components/ozon-content/ozon-content.stories.ts
- angular-workspace/components/pagination/pagination.stories.ts
- angular-workspace/components/progress-bar/progress-bar.stories.ts
- angular-workspace/components/progress-indicator/progress-indicator.stories.ts
- angular-workspace/components/scrollable/scrollable.stories.ts
- angular-workspace/components/selectable/selectable.stories.ts
- angular-workspace/components/slide-toggle/slide-toggle.stories.ts
- angular-workspace/components/toggletip/toggletip.stories.ts
> #3125 [Task] Angular Storybook: Component vervangen met decorators in stories

- CHANGELOG.md
- packages/core/src/components/autosuggest/autosuggest.scss
- packages/core/src/components/autosuggest/autosuggest.tsx
- packages/dso-toolkit/src/components/autosuggest/autosuggest.demo.ts
> #3106 autosuggest  memory leak vervolg

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/change.md
- .github/ISSUE_TEMPLATE/deprecate.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/remove.md
- .github/ISSUE_TEMPLATE/task.md
- CHANGELOG.md
> #3145 [Task] Issue: Nieuwe issues koppelen aan project-id

- CHANGELOG.md
- packages/core/src/components/viewer-grid/viewer-grid.scss
> #3152 [Fixed] Viewer-grid: Het grid pakt volledige hoogte bij inladen

- CHANGELOG.md
- packages/core/src/components/plekinfo-card/plekinfo-card.scss
- packages/core/src/components/plekinfo-card/plekinfo-card.tsx
> #3066 [Added] Plekinfo Card: Chevron wordt niet op de juiste plek weergegeven

- CHANGELOG.md
- packages/core/src/components/document-card/document-card.scss
- packages/core/src/components/document-card/document-card.tsx
- packages/core/src/components/plekinfo-card/plekinfo-card.scss
> #3067 [Added] Document Card: Chevron wordt niet op de juiste plek weergegeven

- CHANGELOG.md
- packages/core/src/components/viewer-grid/viewer-grid.scss
- storybook/src/components/viewer-grid/viewer-grid.core-stories.ts
> #3182 [Fixed] Viewer Grid: Banner valt over filter paneel

- CHANGELOG.md
- website/src/components/StorybookComponent/index.tsx
> #3215 [Task] Website: Deep linking naar component werkt niet

- CHANGELOG.md
- packages/core/src/components/accordion/components/accordion-section-theme-neutral.scss
- packages/core/src/components/expandable/expandable.scss
- packages/dso-toolkit/src/utilities.scss
- storybook/cypress/e2e/expandable.cy.ts
- storybook/src/example-pages/Patronen/animated-form.stories.ts
- website/docs/components/form.mdx
- website/src/components/StorybookComponent/index.tsx
> #3177 [Changed] Form Group: Animaties

- CHANGELOG.md
- packages/dso-toolkit/src/components/label/label.mixins.scss
> #3231 [Fixed] Label: Filter variant border toont zwart ipv donkerblauw

- .github/workflows/ci.yml
- CHANGELOG.md
> #3239 [Task] Build: skip e2e test na zetten van release tag

- CHANGELOG.md
- storybook/cypress/fixtures/image-snapshot-components.json
- storybook/src/components/whitebox/whitebox.css-stories.ts
- storybook/src/components/whitebox/whitebox.css-template.ts
- website/docs/components/whitebox.mdx
- website/docs/voor-maintainers/deprecation-policy.md
> #3172 [Deprecated] Whitebox: Deprecate

- CHANGELOG.md
- packages/core/src/components.d.ts
- packages/core/src/components/legend-item/legend-item.scss
- packages/core/src/components/legend-item/legend-item.tsx
- packages/core/src/components/legend-item/readme.md
- packages/dso-toolkit/src/components/legend-item/legend-item.args.ts
- packages/dso-toolkit/src/components/legend-item/legend-item.models.ts
- packages/dso-toolkit/src/components/legend-item/legend-item.stories-of.ts
- storybook/cypress/e2e/legend-item.cy.ts
- storybook/src/components/legend-item/legend-item.core-stories.ts
- storybook/src/components/legend-item/legend-item.core-template.ts
- Er worden 4 nieuwe snapshots gemaakt in de legend-item.cy.ts test
> #3233 [Changed] Legend Item: Uitbreiden met opties

- .github/workflows/ci.yml
- CHANGELOG.md
- deploy.sh
- package.json
- scripts/update-azure-blob-storage/main.ts
- yarn.lock
> #3270 [Task] Deploy: script blijft niet-bestaande branches verwijderen

- CHANGELOG.md
- storybook/src/components/selectable/selectable.css-stories.ts
- storybook/src/components/selectable/selectable.css-template.ts
- website/docs/components/selectable.mdx
- website/docs/voor-maintainers/deprecation-policy.md
> #3203 [Deprecated] Selectable: Deprecate HTML/CSS implementatie

- CHANGELOG.md
- packages/dso-toolkit/src/components/breadcrumbs/breadcrumbs.args.ts
- packages/dso-toolkit/src/components/breadcrumbs/breadcrumbs.scss
- packages/dso-toolkit/src/components/breadcrumbs/breadcrumbs.stories-of.ts
- packages/dso-toolkit/src/components/breadcrumbs/readme.md
- storybook/cypress/fixtures/image-snapshot-components.json
- storybook/src/components/breadcrumbs/breadcrumbs.css-stories.ts
- storybook/src/components/breadcrumbs/breadcrumbs.css-template.ts
- website/blog/2025-08-30-dso-toolkit-next.mdx
- website/docs/components/breadcrumbs.mdx
> #3210 [Changed] Breadcrumb: Breadcrumb met "s"

- CHANGELOG.md
- packages/core/src/components/header/header.tsx
De 5 testen die faalden omdat het Dropdown Menu niet bestond slagen nu wel (4x) of falen ivm een nieuw imageSnapshot (1x)
> #3351 [Fixed] Header: Dropdown Menu met overflow menu items verschijnt niet

- .github/workflows/ci.yml
- CHANGELOG.md
- angular-workspace/components/header/header.angular-template.ts
- packages/core/src/components.d.ts
- packages/core/src/components/dropdown-menu/dropdown-menu.scss
- packages/core/src/components/dropdown-menu/dropdown-menu.tsx
- packages/core/src/components/header/header.interfaces.ts
- packages/core/src/components/header/header.scss
- packages/core/src/components/header/header.tsx
- packages/core/src/components/header/menu-item.functional-component.tsx
- packages/core/src/components/header/readme.md
- packages/core/src/components/logo/logo.scss
- packages/dso-toolkit/src/components/header/header.args.ts
- packages/dso-toolkit/src/components/header/header.models.ts
- packages/dso-toolkit/src/components/header/header.stories-of.ts
- packages/react/src/components/header/header.react-template.tsx
- storybook/cypress/e2e/header.cy.ts
- storybook/cypress/support/cypress-styling.ts
- storybook/cypress/support/wait-for-components/wait-for-components.ts
- storybook/cypress/support/wait-for-components/wait-for-header.ts
- storybook/src/components/header/header.core-template.ts
- storybook/src/example-pages/content/header.content.ts
- storybook/src/example-pages/toepassingen/beheer/beheer-basis.content.ts
- storybook/src/example-pages/toepassingen/regels-op-de-kaart/documenten.content.ts
- storybook/src/example-pages/toepassingen/samenwerken/samenwerken-gegevens.content.ts
- storybook/src/example-pages/toepassingen/samenwerken/samenwerken-overzicht.content.ts
- website/blog/_-dso-toolkit-next.mdx
> #3289 Header epic
