dso-toolkit/dso-toolkit

components/05-navigation/searchbar/searchbar.config.yml
components/05-navigation/searchbar/searchbar.hbs
src/styles/components/_searchbar.scss

- animatie alleen actief wanneer `dso-animate` op `dso-searchbar` staat

#71 - Searchbar redesign

---

CHANGELOG.md
src/styles/icons/_di.scss
src/styles/mixins/_dso-variables.scss

* Locatie van scg-icons.svg in variabele `$dso-icons-path` ondergebracht (default: `../`).

dso-icons.svg via instelbaar pad inlezen #435

---

CHANGELOG.md
components/Componenten/banner/banner.config.yml
components/Componenten/banner/banner.njk
reference/render/banner--default.html
reference/render/banner--rich-content.html
reference/render/banner--warning.html
reference/render/pagina-met-banner.html
src/styles/components/_banner.scss

Dit is een breaking change, markupvoorschrift is gewijzigd.
---
Er is een toevoeging gedaan met betrekking tot een heading voor de banner tekst. Voor de melding moet een `<h2>` (of bij uitzondering een andere heading, zie documentatie) worden toegevoegd waar de volgende teksten in kunnen staan (let op de dubbele punt):
- danger > `<h2>Storingsmelding:</h2>`
- warning >  `<h2>Onderhoudsmelding:</h2>`
Een valide banner kan er zo uit zien:
```
<section class="banner alert-danger" role="alert">
<div class="container">
<div class="row">
<div class="col-sm-12">
<div class="dso-rich-content">
<h2>
Storingsmelding:
</h2>
<p>Op dit moment ervaren wij een storing in de Vergunningcheck. U kunt wel een aanvraag of melding indienen.</p>
</div>
<button type="button" class="btn btn-link"><span …
```

#767.Banner; WCAG verbeteringen

---

CHANGELOG.md
packages/dso-toolkit/src/styles/components/_pager.scss

Dit is geen breaking change, enkel een deprecation notice.
---
`.pager` zal niet weldra niet meer in de styling voorkomen: er was namelijk al geen markup voorschrift voor, het component en z'n voorbeelden zijn verwijderd in #604 (toen werd het `form-pager`) en deze is uiteindelijk in #670 verwijderd.

#910.Pager deprecaten

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/whitebox/whitebox.njk
packages/dso-toolkit/components/Voorbeelden/Homepage.njk
packages/dso-toolkit/reference/render/homepage.html
packages/dso-toolkit/reference/render/whitebox.html
packages/dso-toolkit/src/styles/components/_whitebox.scss
packages/styling/components/highlight-box.scss

**Breaking** Markup change: de `min-height` is van de `dso-whitebox` en 'dso-whitebox-small` gehaald. Als het nodig is dat de whiteboxes even hoog zijn, dan moet op de omliggende `div.row` de class `dso-equal-heights` toegevoegd worden (https://www.dso-toolkit.nl/16.0.0/components/detail/row-equal-heights.html).

#929.grote whiteboxes aanpassingen

---

packages/dso-toolkit/components/Componenten/form-elements/group-checkboxes.njk
packages/dso-toolkit/components/Componenten/form-elements/group-radios.njk
packages/dso-toolkit/reference/render/accordion--default-met-formulier.html
packages/dso-toolkit/reference/render/dialog--invalid.html
packages/dso-toolkit/reference/render/form--form-horizontal.html
packages/dso-toolkit/reference/render/form--form-vertical.html
packages/dso-toolkit/reference/render/form--simple-form.html
packages/dso-toolkit/reference/render/group-checkboxes--default.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-disabled.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-info-button.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-invalid.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-required.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-valid.html
packages/dso-toolkit/reference/render/group-input--input-text-invalid-input.html
packages/dso-toolkit/reference/render/group-radios--default.html
packages/dso-toolkit/reference/render/group-radios--input-radio-disabled.html
packages/dso-toolkit/reference/render/group-radios--input-radio-inline-info.html
packages/dso-toolkit/reference/render/group-radios--input-radio-inline.html
packages/dso-toolkit/reference/render/group-radios--input-radio-invalid.html
packages/dso-toolkit/reference/render/group-radios--input-radio-required.html
packages/dso-toolkit/reference/render/group-radios--input-radio-valid.html
packages/dso-toolkit/reference/render/modal.html
packages/dso-toolkit/reference/render/wizard-stap-3.html
packages/dso-toolkit/src/styles/components/_form.scss
packages/dso-toolkit/src/styles/components/_info.scss

Dit is een breaking change, markupvoorschrift is gewijzigd.
---
Een `<div>` element mag niet in een `<legend>` element staan. Om het ontwerp te waarborgen is gekozen om de legend te verbergen met een `sr-only` en in plaats daarvan na de `<legend>` een container `<div>` te maken waar een visuele `<span>` in zit met een `aria-hidden`. In deze `<div>` zullen ook de toelichting en de toelichting knop staan.
```
<legend class="sr-only">** INPUT LABEL **</legend>
<div class="dso-label-container">
<span class="control-label" aria-hidden="">
** INPUT LABEL **
</span>
<button type="button" class="btn dso-info-button dso-open" aria-expanded="true">
<span class="sr-only">Toelichting bij vraag</span>
</button>
<div class="dso-info">
** TOELICHTING **
</div>
</div>
```

#996.dso-info-moet-buiten-legend-staan

---

CHANGELOG.md
packages/dso-toolkit/src/styles/components/_anchor.scss
packages/dso-toolkit/src/styles/components/_banner.scss
packages/dso-toolkit/src/styles/components/_info.scss
packages/styling/components/highlight-box.scss

Anchors op een gekleurde achtergrond worden iets anders behandelt dan normale anchors op een witte achtergrond. Het gaat hierbij om de anchors in een lopende tekst.
- De kleur is altijd zwart; default, hover, active, focus, visited
- De underline is alleen aanwezig bij de default state. Bij hover, active, focus en visited dus geen underline
Om het testen te vereenvoudigen heb ik de geraakte componenten hieronder gezet.
Te starten met de componenten in de huidige status:
Anchor: https://dso-toolkit.nl/19.0.0/components/detail/anchor.html
Alert: https://dso-toolkit.nl/19.0.0/components/detail/alert.html
Banner: https://dso-toolkit.nl/19.0.0/components/detail/banner.html
Highlightbox: https://dso-toolkit.nl/19.0.0/components/detail/highlight-box.html
Info: …

#1009.Anchor styling aanpassingen voor componenten met gekleurde achtergrond

---

CHANGELOG.md
packages/dso-toolkit/src/styles/components/_accordion.scss

De accordion heeft twee vormen, waarvan er een uit anchors bestaat. Het is de bedoeling dat de accordion handles met een anchor er hetzelfde uitzien als de variant met een button.
- Geen underline op alle mogelijke states; default, hover, active, focus, voor zowel button als anchor variant
Om het testen te vereenvoudigen heb ik de geraakte componenten hieronder gezet. Let op de verschillende varianten met button en anchor en de compacte variant onder aan.
Te starten met de componenten in de huidige status:
Accordion: https://dso-toolkit.nl/19.0.0/components/detail/accordion.html
En de componenten na aanpassing:
Accordion: https://dso-toolkit.nl/_1008.Accordion-anchor-styling-aanpassingen/components/detail/accordion.html

#1008.Accordion anchor styling aanpassingen

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/form-elements/group-checkboxes.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-input.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-radios.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-search-bar.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-select.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-static.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-textarea.config.yml
packages/dso-toolkit/components/Componenten/form/form.config.yml
packages/dso-toolkit/reference/render/form--form-horizontal.html
packages/dso-toolkit/reference/render/form--form-vertical.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-info-button.html
packages/dso-toolkit/reference/render/group-input--input-text-infobutton-open.html
packages/dso-toolkit/reference/render/group-radios--input-radio-inline-info.html
packages/dso-toolkit/reference/render/group-search-bar--search-bar-infobutton-expanded.html
packages/dso-toolkit/reference/render/group-select--input-select-infobutton-open.html
packages/dso-toolkit/reference/render/group-static--static-infobutton-open.html
packages/dso-toolkit/reference/render/group-textarea--input-textarea-infobutton-open.html
packages/dso-toolkit/reference/render/modal.html
packages/dso-toolkit/src/styles/components/_form.scss
packages/dso-toolkit/src/styles/components/_info.scss

De DSO-info (toelichting blok) staat nu direct onder de vraag/het antwoord. De toelichting die voorheen als laatste kind in de fieldset stond is deprecated.
Situatie voorheen:
Group checkboxen: https://dso-toolkit.nl/19.0.0/components/detail/group-checkboxes.html
Group input: https://dso-toolkit.nl/19.0.0/components/detail/group-input.html
Group radios: https://dso-toolkit.nl/19.0.0/components/detail/group-radios.html
Group searchbar: https://dso-toolkit.nl/19.0.0/components/detail/group-search-bar.html
Group select: https://dso-toolkit.nl/19.0.0/components/detail/group-select.html
Group static: https://dso-toolkit.nl/19.0.0/components/detail/group-static.html
Group textarea: https://dso-toolkit.nl/19.0.0/components/detail/group-textarea.html
Group form: …

#920.toelichting vraag onder antwoorden deprecaten

---

CHANGELOG.md
packages/styling/variables/units.scss

Voor een consequente toepassingen van verticale marges, worden de volgende variabelen gedefinieerd:
```
$dso-vertical-spacing-small: $u1;       //8px
$dso-vertical-spacing-medium: $u2; //16px
$dso-vertical-spacing-large: $u3;      //24px
$dso-vertical-spacing-xlarge: $u4;    //32px

#1042 : Variabelen voor verticale marges

---

CHANGELOG.md
packages/core/src/components.d.ts
packages/core/src/components/alert/alert.tsx
packages/core/src/components/alert/readme.md
packages/dso-toolkit/components/Componenten/alert/alert.config.yml
packages/dso-toolkit/components/Componenten/alert/alert.njk
packages/dso-toolkit/reference/render/alert--alert-with-headings.html
packages/dso-toolkit/reference/render/alert--danger-button.html
packages/dso-toolkit/reference/render/alert--danger.html
packages/dso-toolkit/reference/render/alert--info-button.html
packages/dso-toolkit/reference/render/alert--info.html
packages/dso-toolkit/reference/render/alert--success-button.html
packages/dso-toolkit/reference/render/alert--warning-button.html
packages/dso-toolkit/reference/render/alert--warning.html
packages/dso-toolkit/reference/render/alert--with-role-alert.html

Een geldige alert webcomponent met als status `success` en waarbij de `role="alert"` wordt gezet:
```
<dso-alert status="success" role-alert>## TEKST ##</dso-alert>
```
-----
Het alert webcomponent heeft nu een toegevoegde @Prop genaamd `roleAlert` met type boolean. Wanneer deze op true staat wordt het attribuut `role="alert"` gezet, en wanneer deze false is zal de waarde in het attribuut `undefined` zijn, en dus ook niet tonen. Een extra variant is toegevoegd op de Alert component pagina, die deze `role="alert"` bevat.
Oude situatie:
https://dso-toolkit.nl/19.0.0/components/detail/alert.html
https://dso-toolkit.nl/_986.alert-role-alert/components/detail/alert.html

#986 - Web Component: Alerts niet altijd een role=alert meegeven

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/dropdown-button/dropdown-button.config.js
packages/dso-toolkit/components/Componenten/dropdown-button/dropdown-button.njk
packages/dso-toolkit/reference/render/dropdown-button--dropdown-default-button-align-right.html
packages/dso-toolkit/reference/render/dropdown-button--dropdown-link-button-align-right.html
packages/dso-toolkit/reference/render/dropdown-button--dropdown-primary-button-align-right.html
packages/dso-toolkit/src/styles/components/_dropdown.scss

Voorbeelden toegevoegd voor de rechter uitlijning van het dropdown menu. Class `dso-dropdown-right` op de parent van, of op `.dropdown` zelf zorgt voor een rechter uitlijning:
```
<div class="dropdown dso-dropdown-right">
<button type="button" id="dropdownmenu" aria-haspopup="true" aria-expanded="true" class="btn btn-default">
<span>Actie</span>
</button>
<div class="dropdown-menu">
<ul aria-labelledby="dropdownmenu">
<li class="dso-checked">
<a href="#">10.6.0</a>
</li>
<li>
<a href="#">10.5.0</a>
</li>
</ul>
</div>
</div>
```
```
<div class="dso-dropdown-right">
<div class="dropdown">
<button type="button" id="dropdownmenu" aria-haspopup="true" aria-expanded="true" class="btn btn-default">
<span>Actie</span>
</button>
<div class="dropdown-menu">
<ul aria-labelledby="dropdownmenu">
<li …
```

#961 Dropdown rechts kunnen uitlijnen

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/search-bar/search-bar.njk

In de njk markup was de buttontekst bij de serach-bar hard-coded

#1037 : Instelbare buttontekst mogelijk maken bij search-bar

---

CHANGELOG.md
packages/dso-toolkit/src/styles/components/_form.scss

In sommige gevallen is het gebruik van headings in een legend gewenst (en ook toegestaan want phrasing content). Alleen zijn in deze gevallen de standaard verticale margins van de headings niet gewenst.

#1032 : geen marge rond headings in legend

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/accordion/accordion.njk

In de njk markup is het mogelijk gemaakt dat er een definition-list in een geneste accordion geplaatst kan worden, dus niet alleen op het hoogste nivo.

#1034 : Definition lists in geneste accordion

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/form-elements/group-static.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-static.njk
packages/dso-toolkit/reference/render/form--form-horizontal.html
packages/dso-toolkit/reference/render/form--form-vertical.html
packages/dso-toolkit/reference/render/group-static--default.html
packages/dso-toolkit/reference/render/group-static--static-editbutton.html
packages/dso-toolkit/reference/render/group-static--static-infobutton-open.html
packages/dso-toolkit/reference/render/group-static--static-infobutton.html
packages/dso-toolkit/reference/render/modal.html
packages/dso-toolkit/src/styles/components/_button.scss
packages/dso-toolkit/src/styles/components/_form.scss

In een `.dso-field-container` hoeven platte waarden niet in een `<p>`worden gezet (verticale ruimte wordt namelijk elders al vemaakt).

#1036.aanpassen edit mogelijkheid bij group static

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/form-elements/group-checkboxes.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-checkboxes.njk
packages/dso-toolkit/components/Componenten/form-elements/group-radios.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-radios.njk
packages/dso-toolkit/components/Componenten/info-button/info-button.njk
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-info-button.html
packages/dso-toolkit/reference/render/group-checkboxes--input-checkbox-static-info.html
packages/dso-toolkit/reference/render/group-radios--input-radio-inline-info.html
packages/dso-toolkit/reference/render/group-radios--input-radio-static-info.html
packages/dso-toolkit/reference/render/omgevingsoverleg.html

* not(not()) om null 'falsy' te behandelen
* expliciete infoOpen: false bij infoText Closed
* geen loze dso-info vanwege deprecation

#1078 Group checkboxes: bad value bij aria-expanded

---

CHANGELOG.md
packages/dso-toolkit/libs/bootstrap/_variables.scss
packages/dso-toolkit/src/styles/components/_card.scss
packages/dso-toolkit/src/styles/components/_definition-list.scss
packages/dso-toolkit/src/styles/components/_footnotes.scss
packages/dso-toolkit/src/styles/components/_modal.scss
packages/dso-toolkit/src/styles/components/_steps.scss
packages/styling/components/table.scss

_Geen_
-----
Oude kleuren zijn nu vervangen in de $grijs-20 (#ccc) variant
Oude situatie:
https://dso-toolkit.nl/21.3.0/components/detail/cards.html
https://dso-toolkit.nl/21.3.0/components/detail/footnotes.html
https://dso-toolkit.nl/21.3.0/components/detail/form-steps.html
https://dso-toolkit.nl/21.3.0/components/detail/modal.html
https://dso-toolkit.nl/21.3.0/components/detail/panel.html
https://dso-toolkit.nl/21.3.0/components/detail/omgevingsoverleg.html
https://dso-toolkit.nl/21.3.0/components/detail/rich-content.html
https://dso-toolkit.nl/21.3.0/components/detail/table.html
https://dso-toolkit.nl/_1024.Scheidingslijnen-styling-consistent/components/detail/cards.html …

#1024.Scheidingslijnen-styling-consistent

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/progress-indicator/progress-indicator.config.yml
packages/dso-toolkit/components/Componenten/progress-indicator/progress-indicator.njk
packages/dso-toolkit/reference/render/progress-indicator--spinner-large-block.html
packages/dso-toolkit/reference/render/progress-indicator--spinner-medium-block-background.html
packages/dso-toolkit/reference/render/progress-indicator--spinner-small-block.html
packages/dso-toolkit/src/styles/components/_progress-indicator.scss

Toevoeging class `dso-block` zorgt voor horizontaal en verticaal gecentreerde progress-indicator;
icm. class `dso-small` zorgt voor een (afhankelijk van de inhoud minimaal) 48px hoge progress indicator;
icm. class `dso-medium` zorgt voor een (afhankelijk van de inhoud minimaal) 64px hoge progress indicator;
icm. class `dso-large` zorgt voor een (afhankelijk van de inhoud minimaal) 96px hoge progress indicator;
icm. class `dso-gray` zorgt dit voor een lichtgrijze achtergrond.
Voorbeeld: 
```
<div class="dso-progress-indicator dso-progress-indicator-looping dso-medium dso-block dso-gray" role="progressbar" aria-valuetext="Een moment geduld alstublieft.">
<div class="dso-progress-indicator-spinner"></div><span class="dso-progress-indicator-label">Een moment …
```

#1083 : Variant toevoegen voor Progress Indicator

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/navigations/navigations.njk
packages/dso-toolkit/reference/render/404pagina.html
packages/dso-toolkit/reference/render/beheer-basis.html
packages/dso-toolkit/reference/render/full-width.html
packages/dso-toolkit/reference/render/header.html
packages/dso-toolkit/reference/render/homepage.html
packages/dso-toolkit/reference/render/landingspagina.html
packages/dso-toolkit/reference/render/navigations--default.html
packages/dso-toolkit/reference/render/navigations--secondary.html
packages/dso-toolkit/reference/render/overzicht-samenwerkingen.html
packages/dso-toolkit/reference/render/pagina-met-banner.html
packages/dso-toolkit/reference/render/row-equal-heights.html
packages/dso-toolkit/reference/render/zoeken-in-lijst-cards.html
packages/dso-toolkit/theme/js/components/browser.js

Een actief navigatie item dient nu een `aria-current="page"` op de `<a>` te bevatten.
```
<ul class="dso-nav dso-nav-main">
<li class="dso-active">
<a href="#" aria-current="page">
Home
</a>
</li>
<li>
<a href="#">
Vergunningcheck
</a>
</li>
</ul>
```
-----
Oude situatie:
https://dso-toolkit.nl/24.0.0/components/detail/navigations.html
https://dso-toolkit.nl/_1131.Navigations-aria-current-page-toevoegen/components/detail/navigations.html

#1131.Navigations-aria-current-page-toevoegen

---

CHANGELOG.md
packages/dso-toolkit/components/Componenten/navigations/navigations.njk
packages/dso-toolkit/reference/render/404pagina.html
packages/dso-toolkit/reference/render/beheer-basis.html
packages/dso-toolkit/reference/render/full-width.html
packages/dso-toolkit/reference/render/header.html
packages/dso-toolkit/reference/render/homepage.html
packages/dso-toolkit/reference/render/landingspagina.html
packages/dso-toolkit/reference/render/navigations--default.html
packages/dso-toolkit/reference/render/overzicht-samenwerkingen.html
packages/dso-toolkit/reference/render/pagina-met-banner.html
packages/dso-toolkit/reference/render/row-equal-heights.html
packages/dso-toolkit/reference/render/zoeken-in-lijst-cards.html
packages/dso-toolkit/src/styles/components/_modal.scss

De `button` in de `dso-navbar-header` moet een `aria-expanded` attribuut krijgen gerelateerd aan de opened-state van het menu.
```
<nav class="dso-navbar">
<div class="dso-navbar-header">
<button type="button" class="dso-navbar-toggle btn btn-default" aria-expanded="false">
<dso-icon icon="bars"></dso-icon>
<span class="sr-only">Menu</span>
</button>
</div>
<ul class="dso-nav dso-nav-main">
<li class="dso-active">
<a href="#">
Home
</a>
</li>
<li>
<a href="#">
Vergunningcheck
</a>
</li>
</ul>
</nav>
```
-----
Het `aria-expanded` attribuut is in de huidige dso-toolkit niet te testen doormiddel van de checkbox "Open/sluit" die nu bij de navigations staat. Data driven werkt het wel goed, en is dit getest. Dit werkt zoals het ook bij …

#1134.Navigations: aria-expanded en label hamburger knopje aanpassen

---

CHANGELOG.md
packages/sources/src/components/alert/alert.scss
packages/sources/src/components/banner/banner.scss
packages/sources/src/components/info/info.scss

Geen
-----
**Anchor**
Oud: https://dso-toolkit.nl/30.0.0/components/detail/alert.html
Nieuw: https://dso-toolkit.nl/_1281.Anchor-link-styling-op-gekleurde-achtergrond-niet-gelijk/components/detail/alert.html
**Banner**
Oud: https://dso-toolkit.nl/30.0.0/components/detail/banner.html
Nieuw: https://dso-toolkit.nl/_1281.Anchor-link-styling-op-gekleurde-achtergrond-niet-gelijk/components/detail/banner.html
**Highlight box**
Oud: https://dso-toolkit.nl/30.0.0/components/detail/highlight-box.html
Nieuw: https://dso-toolkit.nl/_1281.Anchor-link-styling-op-gekleurde-achtergrond-niet-gelijk/components/detail/highlight-box.html
**Info**
Oud: https://dso-toolkit.nl/30.0.0/components/detail/info.html
Nieuw: …

#1281.Anchor link styling op gekleurde achtergrond niet gelijk

---

CHANGELOG.md
packages/css/src/components/context/context.scss
packages/css/src/components/context/context.template.ts
packages/dso-toolkit/components/Voorbeelden/10-Patronen/filterblok.njk
packages/dso-toolkit/components/Voorbeelden/20-Toepassingen/10-Aanvragen/activiteiten.njk
packages/dso-toolkit/reference/render/activiteiten.html
packages/dso-toolkit/reference/render/filterblok.html

Dit is een breaking change, de markup is gewijzigd voor het gebruik bij een fieldset. Het is niet langer de bedoeling dat de `.dso-context-wrapper` op een `fieldset` staat, en dat de `.dso-context-label` op de `legend` staat.
In plaats daarvan is het stukje `dso-context-wrapper` en de elementen die daar in horen; `dso-context-label` en `dso-context-container` een eigen eilandje geworden. Let wel op de `.sr-only` die op de `legend` gezet dient te worden, en de daarbij behorende `aria-hidden="true"` op de `dso-context-label`
Een geldige code ziet er nu zo uit:
```
<fieldset>
<legend class="sr-only">
${label}
</legend>
<div class="dso-context-wrapper">
<span class="dso-context-label" aria-hidden="true">
${label}
</span>
<div class="dso-context-container"> …
```

#1274.Gedrag Context Component bij lange labels en/of grotere interactieve onderdelen

---

CHANGELOG.md
packages/css/src/components/input-number/input-number.template.ts
packages/dso-toolkit/components/Componenten/form-elements/group-input-number.config.yml
packages/dso-toolkit/components/Componenten/form-elements/group-input-number.njk
packages/dso-toolkit/components/Componenten/input-number/input-number.config.yml
packages/dso-toolkit/components/Componenten/input-number/input-number.njk
packages/dso-toolkit/components/Componenten/list-button/list-button.njk
packages/dso-toolkit/reference/render/activiteiten.html
packages/dso-toolkit/reference/render/group-input-number--input-number-maximum-limit.html
packages/dso-toolkit/reference/render/group-input-number--input-number-minimum-limit.html
packages/dso-toolkit/reference/render/group-input-number--no-label.html
packages/dso-toolkit/reference/render/input-number--no-label.html
packages/dso-toolkit/reference/render/list-button--button-met-extra-label-en-input-number.html
packages/dso-toolkit/reference/render/list-button--button-met-input-number-selected.html
packages/dso-toolkit/reference/render/list-button--button-met-input-number.html
packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst-en-input-number-en-extra-label.html
packages/dso-toolkit/reference/render/list-button--button-met-lange-optionele-tekst-en-input-number.html
packages/dso-toolkit/reference/render/list-button--button-met-optionele-tekst-en-input-number-en-extra-label.html
packages/dso-toolkit/reference/render/list-button--button-met-optionele-tekst-en-input-number.html
packages/sources/src/components/input-number/input-number.stories.ts

* css compontent: min en max zijn geen boolean attributes, en aria-label als geen label
* group input number: kan al zelf het label geven, en doorgeven min en max
* input-number min en max zijn ints, geen strings, en aria-label als niet zelf een label of reeds gelabeld (door bv. group input)

#1386 Input-type number moet altijd gelabeled zijn

---

CHANGELOG.md
packages/css/src/components/image/readme.md
packages/sources/src/components/image/image.args.ts
packages/sources/src/components/image/image.scss
packages/sources/src/components/image/image.stories.ts

Met deze change zijn de varianten `.img-rounded` en `.img-thumbnail` van het `image` HTML/CSS Component deprecated.

#1188.Storybook CSS Component - Image

---

CHANGELOG.md
packages/core/src/components.d.ts
packages/core/src/components/badge/badge.tsx
packages/core/src/components/badge/readme.md
packages/css/src/components/badge/badge.template.ts
packages/dso-toolkit/components/Componenten/badge/badge.config.js
packages/dso-toolkit/reference/render/badge--badge-outline.html
packages/sources/src/components/badge/badge.args.ts
packages/sources/src/components/badge/badge.scss
packages/sources/src/components/badge/badge.stories.ts

Er is een nieuwe variant voor `Badge` geintroduceerd. Je kunt hiervoor de support-class `badge-outline` gebruiken.
Correcte markup ziet er zo uit:
```
<span class="dso-badge badge-outline">Badge tekst</span>
```

#1534.Badge Default Outline toevoegen

---

CHANGELOG.md
packages/core/src/components.d.ts
packages/core/src/components/map-base-layers/map-base-layers.tsx
packages/core/src/components/map-base-layers/readme.md
packages/core/src/components/map-overlays/map-overlays.tsx
packages/core/src/components/map-overlays/readme.md
packages/core/src/components/selectable/selectable.tsx

Vanuit `@dso-toolkit/leaflet` worden `<dso-map-controls />`, `<dso-map-overlays />` en `<dso-map-baselayers />` aangeroepen. Baselayer en Overlays (samen de "Map Layer componenten") roepen vervolgens `<dso-selectable />` aan.
Een "Map Layer component" wordt geinstantieerd. Dit component accepteert een `@Prop() group: string`. Als er geen `group` wordt gegeven, wordt er een GUID gegenereerd.
De `group` wordt als `name` voor de selectables van een groep layers gebruikt. Hiermee worden de selectables gekoppeld.
Is dit OK of is het belangrijk dat `name` een herkenbare/toegankelijke value krijgt? Zo ja: Dan zal er ook een change in `@dso-toolkit/leaflet` en `@dso-toolkit/react-leaflet` moeten komen. ~De "group identifier" moet immers worden meegegeven door de afnemer.~ edit: Niet waar, de name …

#1573 Fixed: Map controls: onjuist toetsenbord gedrag keuzerondjes

---

CHANGELOG.md
packages/css/src/components/document-list/document-list.scss
packages/css/src/components/document-list/document-list.template.ts

De markup is aangepast zodat `.dso-document-list-item` nu de wrapper is van `.dso-document-list-item-heading` en (de toegevoegde nieuwe) `.dso-document-list-item-content`. De vulling die oorspronkelijk in `.dso-document-list-item` stond, staat nu in `.dso-document-list-item-heading`.
Geldige markup ziet er bijvoorbeeld zo uit:
```
<div class="dso-document-list-item">
<div class="dso-document-list-item-heading">
<h2>
Omgevingsplan gemeente Gouda
</h2>
<div class="dso-document-list-item-container">
<p class="dso-document-list-item-type">
Omgevingsplan
</p>
<p class="dso-document-list-item-owner">
Gemeente Gouda
</p>
<p class="dso-document-list-item-status">
<span class="dso-badge badge-warning">
Ontwerp
</span>
Bekendgemaakt 01-03-2021
</p>
<a href="#" …
```

#1657.Document-Item-uitbreiden-met-container-voor-regels

---

CHANGELOG.md
packages/css/src/components/document-header/document-header.content.ts
packages/css/src/components/document-header/document-header.scss
packages/css/src/components/document-header/document-header.template.ts
packages/sources/src/components/badge/badge.scss

Breaking change, de markup is aangepast. Een geldige markup ziet er nu zo uit:
```
<div class="dso-document-header-container">
<div class="dso-document-header-owner-wrapper">
<p class="dso-document-header-type">#</p>
<p class="dso-document-header-owner">#</p>
</div>
<button type="button" class="dso-document-header-map-action">#</button>
<div class="dso-document-header-features-wrapper">
<button type="button" class="dso-document-header-toggle-features" aria-expanded="false">
<span>Meer kenmerken</span>
</button>
</div>
<div class="dso-document-header-status-wrapper">
<p class="dso-document-header-status">
<span class="dso-label  dso-label-bright ">
<span class="sr-only">: </span>
in werking
</span>
Gepubliceerd 03-03-2021
<button type="button" class="dso-document-header-toggle-status" …
```

#1681.aanpassing document header

---

CHANGELOG.md
packages/core/src/components/info/info.tsx
packages/css/src/components/info/info.template.ts

Het sluitknopje is nu onderaan in de DOM van het component verplaatst.
Geldige markup ziet er zo uit:
```
<div class="dso-info">
<div class="dso-rich-content">
##CONTENT##
</div>
<button type="button">
<span class="sr-only">Sluiten</span>
</button>
</div>
```

#1707 - Info: sluitknopje in DOM onderaan

---

CHANGELOG.md
packages/core/src/components/progress-bar/progress-bar.tsx
packages/core/src/components/progress-indicator/progress-indicator.scss
packages/core/src/components/progress-indicator/progress-indicator.tsx
packages/css/src/components/progress-bar/progress-bar.template.ts
packages/css/src/components/progress-indicator/progress-indicator.template.ts
packages/dso-toolkit/reference/render/progress-bar--default.html
packages/dso-toolkit/reference/render/progress-bar--non-default-values.html
packages/sources/src/components/progress-bar/progress-bar.scss

Een aantal elementen zijn aangepast naar `<span>` elementen.
Geldige markup progressbar:
```
<div class="progress">
<span class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">
<span style="width: 60%"></span>
</span>
<span id="progress-bar-label">
Genereren export: nog ongeveer 4 minuten.
</span>
</div>
```
Geldige markup progress-indicator:
```
<div class="dso-progress-indicator dso-small ">
<span class="dso-progress-indicator-spinner" role="progressbar" aria-labelledby="progress-indicator-label"></span>
<span id="progress-indicator-label" class="dso-progress-indicator-label">
Resultaten laden: een moment geduld alstublieft.
</span>
</div>
```

#1714.progress bar indicator wcag verbeteringen

---

CHANGELOG.md
packages/core/src/components/header/header.scss
packages/core/src/components/header/header.template.ts
packages/css/src/components/header/header.scss

Voorheen werd er een `height="40"` op de `img` in de `slot="logo"` gezet. Deze is nu weggehaald, de maat wordt dmv stijling bepaald.

#1763 Header styling verbeteringen

---

CHANGELOG.md
packages/core/src/components/accordion/components/accordion-section-theme-compact.scss
packages/core/src/components/accordion/components/accordion-section-theme-conclusion.scss
packages/core/src/components/accordion/components/accordion-section-theme-default.scss
packages/core/src/components/accordion/components/accordion-section.scss
packages/core/src/components/accordion/components/accordion-section.tsx
packages/css/src/components/accordion/accordion-theme-compact.scss
packages/css/src/components/accordion/accordion-theme-conclusion.scss
packages/css/src/components/accordion/accordion-theme-default.scss
packages/css/src/components/accordion/accordion.scss
packages/react/src/components/accordion/accordion.react-template.tsx
packages/sources/src/components/accordion/accordion.variables.scss
packages/storybook/src/components/accordion/accordion.core-template.ts
packages/storybook/src/components/accordion/accordion.css-template.ts

* Als de attachmentcount van 1 naar 0 gaat dan verschijnt een 0 achter de heading.
* Styling: de onderste corners moeten radius 0 krijgen in uitgeklapte toestand
* De heading control lijkt geen effect te hebben, mogelijk de property ook niet.
* Wanneer de titel multi-line is centreert de tekst ongewenst.
* css variants
* css section heading undefined
* Stijling nested accordion
* Stijling compact accordion

#1826 Webcomponent Accordion: Algemene verbeteringen

---

CHANGELOG.md
packages/core/src/components/ozon-content/nodes/figuur.node.tsx

bij de <Figuur> node treedt dit op

#1881 Fixed: dso-ozon-content kan lege titels/bijschrift div renderen bij image-overlay

---

CHANGELOG.md
packages/core/src/components/modal/modal.tsx
storybook/cypress/e2e/modal.cy.ts
storybook/src/components/modal/modal.css-template.ts
website/blog/2023-01-18-dso-toolkit-51.0.0.mdx

Ik vraag mij nu af of dit niet voorwaardelijk moet?
Als de content wel past en er geen scrollbare content is, zit die `tabindex="0"` dan in de weg?
Voor het Web Component kunnen we dat best wel oplossen. Met 'n MutationObserver kunnen we de slotted content observen en alleen als nodig het attribuut `tabindex="0"` zetten.
Voor het HTML/CSS component zal het bij voorschriften blijven.
@timveld wat denk jij?

#1989 Fixed: Modal body niet bereikbaar met toetsenbord bij scrollbaar gebied.

---

CHANGELOG.md
packages/core/src/components.d.ts
packages/core/src/components/accordion/accordion.interfaces.ts
packages/core/src/components/accordion/components/accordion-section.interfaces.ts
packages/core/src/components/accordion/components/accordion-section.tsx
packages/core/src/components/expandable/expandable.tsx
packages/dso-toolkit/src/components/accordion/accordion.models.ts
packages/react/src/components/accordion/accordion.react-template.tsx
storybook/cypress/e2e/accordion.cy.ts

Na lang zoeken naar de oorzaak, bleek het de verplaatsing van `this.instantiateAnimation();` buiten de `debounce` te zijn. Maar het was belangrijk dat het zetten van `this.bodyheight` binnen de `debounce` eerst werd afgerond voordat deze call werd gedaan.

#2245 Accordion animatie verspringt

---

CHANGELOG.md
packages/core/src/components/selectable/selectable.scss

De `dso-selectable-input-wrapper` had een `inline` context maar dit zou volgens het altijd strenge Firefox `inline-block` moeten zijn (er staat ook een min-height waarde op dit element, maar Firefox geeft ook aan dat deze op een `inline` element geen waarde heeft).
Resultaat:

#2318 Selectable: Label in Web Component gaat stuk in Firefox

---

CHANGELOG.md
packages/dso-toolkit/src/components/pagination/pagination.mixins.scss

min-inline-size i/o width, small padding added to keep characters away from edge
50% border-radius set to explicit 1rem to facilitate pill-shape with 4+ characters

#2541 [Fixed] Pagination: Long numbers overlap

---

CHANGELOG.md
packages/core/src/components/advanced-select/advanced-select.models.ts
packages/core/src/components/advanced-select/advanced-select.scss
packages/core/src/components/advanced-select/advanced-select.tsx
packages/dso-toolkit/src/components/advanced-select/advanced-select.content.ts
packages/dso-toolkit/src/components/advanced-select/advanced-select.models.ts
packages/dso-toolkit/src/components/advanced-select/advanced-select.variables.scss

Ik heb het geimplementeerd op basis van het wel of niet hebben van een `value`. Opties met value werken gewoon zoals voorheen maar opties zonder value (wat normaal gesproken niet zou voorkomen voor werkende opties) hebben nu deze nieuwe styling.

#2587 Advanced Select: Placeholder toevoegen

---

CHANGELOG.md
packages/core/src/components/ozon-content/nodes/table.node/colspec/colspec-mapper.ts
packages/core/src/components/ozon-content/nodes/table.node/colspec/colspec.interface.ts
packages/core/src/components/ozon-content/nodes/table.node/table-cell.tsx
packages/core/src/components/ozon-content/nodes/table.node/table.node.tsx
packages/dso-toolkit/src/components/ozon-content/ozon-content.content.ts
packages/dso-toolkit/src/components/table/table.mixins.scss
packages/dso-toolkit/src/components/table/table.scss

In deze PR zijn geïmplementeerd 3 van de 6 attributen beschreven in het issue #2423. Te weten rowsep, colsep en frame. Mbt. tot de attributen tabstyle en orient zijn er geen voorbeelden gevonden, waarop dit van toepassing is.
Mbt. attribuut pgwide: deze lijkt geen betekenis te hebben binnen de context van DSO.

#2423 Ozon Content: Tabel toevoegingen STOP implementeren inOzon documentweergave

---

CHANGELOG.md
packages/core/src/components/annotation-button/annotation-button.scss
packages/core/src/components/annotation-output/annotation-output.scss
packages/core/src/components/document-component/document-component.scss
packages/core/src/components/document-component/document-component.tsx

In de storybook Document Component Demo en IMRO loop ik tegen het issue aan dat de class .sr-only niet werkt, dus is of "Invouwen" of "Uitvouwen" in beeld. Ik begrijp niet waarom die niet werkt.

#2480 Document Component: titel knop mist aria expanded en sluit voor titel tekst

---

CHANGELOG.md
packages/core/src/components/modal/modal.tsx
packages/core/src/components/modal/readme.md
packages/dso-toolkit/src/components/modal/modal.scss
packages/dso-toolkit/src/components/modal/readme.md
website/blog/2023-10-20-dso-toolkit-62.0.0.mdx
website/blog/2024-04-15-dso-toolkit-62.19.0.mdx
website/blog/authors.yml

- display: none rule removed
- made selector for overflow: hidden on the body smarter: detects modal (element AND webcomponent) when it is open/present.
- media query for body overflow not really needed, so it's gone

#2610 [Fixed] Modal: Vanishes below 768px viewport

---

CHANGELOG.md
packages/dso-toolkit/src/components/form/content/files.content.ts
packages/dso-toolkit/src/components/form/form-groups/files/form-group-files.scss
packages/dso-toolkit/src/components/form/models/form-group-files.model.ts
storybook/src/components/form/form-group-files.css-template.ts

Zie ook gerelateerd issue https://github.com/dso-toolkit/dso-toolkit/issues/2644: die nog gefixt mag worden. Nu toont het icon spinner nog niet.
Tevens de positie van het Warning icoon gewijzigd: staat nu direct achter de naam van het geüploade document.
En, omdat het warning icon getoond wordt, is het document vertrouwelijk, dus heb ik de checkbox aangezet.
Hier mag UX (@MYpenburg) naar kijken.
Zie https://storybook.dso-toolkit.nl/_2616-From-Group-Files--Ondersteuning-voor-een-spinner--progress-indicator--tijdens-upload-van-bestand/?path=/story/html-css-form-groups-files--files

#2616 Form Group Files: Ondersteuning voor een spinner (progess indicator) tijdens upload van bestand

---

CHANGELOG.md
packages/core/src/components/tooltip/tooltip.scss

#2658 [Fixed] Tooltip: Long words overflow box

---

CHANGELOG.md
packages/core/src/components/mark-bar/mark-bar.scss

`cursor: pointer` on *all* buttons within Mark Bar

#2806 [Fixed] Mark Bar: Pointer on empty field button

---

CHANGELOG.md
packages/core/src/components/image-overlay/image-overlay.tsx

Zie https://github.com/dso-toolkit/dso-toolkit/issues/2808#issuecomment-2407297391

#2808 [Fixed] Ozon Content: Een Figuur zonder Titel of alt kan niet worden ingezoomd

---

CHANGELOG.md
packages/dso-toolkit/src/components/delete/delete.mixins.scss

Added browser-hack targeting Firefox, replacing font in `<del>` element.

#2424 [Fixed] Webfont Asap: Strikethrough in Firefox

---

CHANGELOG.md
packages/core/src/components/card/card.scss
packages/core/src/components/document-card/document-card.scss
packages/core/src/components/plekinfo-card/plekinfo-card.scss
packages/dso-toolkit/src/components/card/card.scss
packages/react/src/components/card/card.react-template.tsx

Bijvoorbeeld r111-123 in [packages/dso-toolkit/src/components/card/card.scss](https://github.com/dso-toolkit/dso-toolkit/compare/%232828-card--internalize-webcomponent-styling?expand=1#diff-eb00d0066a2c1cfd6f6d880acecbfc5b1a11b7a07373bfbb7282f70026a6dcf3) zullen nooit werken vanuit `::slotted` binnen een constructed stylesheet.
Update 28/29-11: ^^ uit de 'light dom'-scss de `[slot="interaction"]` en `[slot="interactions"]` selectors verwijderd, omdat ze op die plek zonder prefix een te groot conflictrisico vormden. zonder die css blijft de core-versie vooralsnog overeind.

#2828 card  internalize webcomponent styling

---

CHANGELOG.md
packages/dso-toolkit/package.json

#2955 [Fixed] Icon mixins: Spritesheet di.svg niet beschikbaar in dso-toolkit package

---

CHANGELOG.md
packages/core/src/components/annotation/annotation.scss

#2925 [Fixed] Annotation (Activiteit): Lange tekst component drukt Slide Toggle weg

---

CHANGELOG.md
packages/core/src/components/document-component/document-component.tsx
storybook/cypress/e2e/document-component.cy.ts

#2929 [Changed] Document Component: Tooltip bij Ontwerp wijzigen

---

CHANGELOG.md
packages/core/src/components/ozon-content/nodes/ext-ref.node.tsx
packages/core/src/components/ozon-content/ozon-content.scss
storybook/cypress/e2e/ozon-content.cy.ts

**Testen:**
- Instructies: Copy de url en check of de sr-only text is verdwenen
- Url: https://storybook.dso-toolkit.nl/_2926-ozon-content-selectie--copy-to-clipboard-without-sr-only/?path=/story/core-ozon-content--ext-io-ref

#2926 [Changed] Ozon Content: Selectie kopieren naar klembord zonder sr-only teksten

---

CHANGELOG.md
packages/core/src/components/slide-toggle/slide-toggle.scss
packages/core/src/components/slide-toggle/slide-toggle.tsx

- De slide-toggle e2e faalt vanwege de 2px padding die we toepassen

#2946 [Changed] Slide Toggle: Uitlijning klopt niet met titel in Annotation component 

---

CHANGELOG.md
packages/core/src/components/accordion/components/accordion-section-theme-compact.scss
packages/core/src/components/accordion/components/accordion-section-theme-default.scss
packages/core/src/components/accordion/components/accordion-section.scss
packages/core/src/components/accordion/components/accordion-section.tsx
packages/dso-toolkit/src/components/accordion/accordion-theme-compact.scss
packages/dso-toolkit/src/components/accordion/accordion-theme-default.scss
packages/dso-toolkit/src/components/accordion/accordion.scss
storybook/cypress/e2e/accordion.cy.ts
storybook/src/components/accordion/accordion.css-template.ts

#2995 [Changed] Accordion: Status zonder underline tonen

---

CHANGELOG.md
packages/dso-toolkit/src/components/accordion/accordion.stories-of.ts
packages/react/src/components/accordion/accordion.content.tsx
packages/react/src/components/accordion/accordion.stories.tsx
storybook/cypress/e2e/accordion.cy.ts
storybook/src/components/accordion/accordion.content.ts
storybook/src/components/accordion/accordion.core-stories.ts
storybook/src/components/accordion/accordion.css-stories.ts
storybook/src/components/accordion/accordion.css-template.ts

#2991 [Task] Accordion: Verbeter het etaleren van de `Nested` Accordion

---

CHANGELOG.md
packages/core/package.json
packages/core/stencil.config.ts
patches/@stencil+angular-output-target+0.7.1.patch
website/docs/voor-maintainers/dependencies-update-procedure.md
yarn.lock

Ik heb lokaal een separaat Angular 19 project aangemaakt. Daarin heb ik `@dso-toolkit/core`, `@dso-toolkit/angular` en `dso-toolkit` geïnstalleerd. Vervolgens heb ik in mijn lokale workspace van dso-toolkit op de branch van deze PR `yarn` en `yarn patch-package` gedaan. Daarna een `yarn build`. Vervolgens heb ik de inhoud van `angular-workspace/dist/component-library` gekopieerd naar `node_modules/@dso-toolkit/angular` van het separate Angular 19 project. In de `app.component.html` heb ik 
```angular
<dso-survey-rating (dsoClose)="handleClose($event)" …
```

#3058 [Fixed] "@stencil/angular-output-target": downgrade naar versie 0.7.1 inclusief patch

---

CHANGELOG.md
packages/dso-toolkit/src/components/form-buttons/form-buttons.args.ts
packages/dso-toolkit/src/components/form-buttons/form-buttons.models.ts
packages/dso-toolkit/src/components/form-buttons/form-buttons.scss
packages/dso-toolkit/src/components/form-buttons/form-buttons.stories-of.ts
packages/dso-toolkit/src/components/form/form-single-page.scss
packages/dso-toolkit/src/components/form/form.args.ts
packages/dso-toolkit/src/components/form/form.models.ts
packages/dso-toolkit/src/components/form/form.scss
packages/dso-toolkit/src/components/form/form.stories-of.ts
packages/dso-toolkit/src/global/spacing.scss
storybook/cypress/fixtures/image-snapshot-components.json
storybook/src/components/form-buttons/form-buttons.css-stories.ts
storybook/src/components/form-buttons/form-buttons.css-template.ts
storybook/src/components/form/form.css-stories.ts
storybook/src/components/form/form.css-template.ts
website/docs/components/form/form-buttons.mdx

#3013 [Changed] Verticaal Ritme: afstand boven en onder knoppenbalk naar 32px

---

CHANGELOG.md
packages/core/src/components/list-button/list-button.tsx
storybook/cypress/e2e/document-component.cy.ts
storybook/cypress/support/commands.ts
storybook/cypress/support/e2e.ts
storybook/package.json
yarn.lock

We maken nu gebruik van de npm-package `cypress-wait-for-stable-dom` met de default options. 
Zie: https://github.com/narinluangrath/cypress-wait-for-stable-dom.
De overwrite van het Cypress command `screenshot` heb ik aangepast. Op deze centrale plek wordt nu altijd `waitForStableDom()` uitgevoerd, voordat het screenshot genomen wordt. 🙏 .
De diff `should be accessible -- dropdown menu.diff.png` van wordt veroorzaakt doordat nu (voor het eerst) lang genoeg wordt gewacht wordt, voordat het screenshot genomen wordt.
Er zijn 12 nieuwe screenshot voor Document Component: die zijn …

#2934 [Task] Document Component: flaky e2e tests verbeteren

---

CHANGELOG.md
storybook/cypress/support/image-snapshot-voorbeeldpaginas.ts

66 falende tests: 2 x 33. In `storybook/cypress/fixtures/image-snapshot-voorbeeldpaginas.json` staan 33 voorbeeldpagina's en patronen. Deze screenshotten we  2x: 1x met de core en 1 x met de html/css implementatie. We hebben derhalve 66 nieuwe screenshots in de baseline.

#3032 [Task] Voorbeeldpagina's: activeer visueel regressietesten

---

CHANGELOG.md
packages/core/src/components/accordion/components/accordion-section-theme-compact-black.scss
packages/core/src/components/accordion/components/accordion-section-theme-compact.scss
packages/core/src/components/accordion/components/accordion-section-theme-neutral.scss
packages/core/src/components/accordion/components/accordion-section.scss
packages/dso-toolkit/src/components/accordion/accordion-theme-compact.scss
packages/dso-toolkit/src/components/accordion/accordion-theme-default.scss
packages/dso-toolkit/src/components/accordion/accordion.scss
storybook/cypress/e2e/accordion.cy.ts

- Action-list heeft een padding wijziging waardoor er een diff ontstaan met het icon van de neutral variant
- Er worden twee nieuwe screenshots gemaakt van de accordion

#3042 [Changed] Accordion: Kleine visuele verbeteringen

---

CHANGELOG.md
packages/core/src/components/logo/logo.scss
storybook/cypress/e2e/logo.cy.ts

- **Er is een nieuwe snapshot wanneer het ribbon attribuut is gevuld en het label-url niet**

#3101 [Fixed] Logo: Ribbon uit positie wanneer logo-url aanwezig is en label-url afwezig is

---

CHANGELOG.md
packages/core/src/components.d.ts
packages/core/src/components/survey-rating/readme.md
packages/core/src/components/survey-rating/survey-rating.tsx

#3046 [Added] Survey Rating: Vraagteken achter de vraag en role alert toevoegen

---

CHANGELOG.md
packages/core/src/components/list-button/list-button.scss
packages/core/src/components/list-button/list-button.tsx

#3116 [Changed] ListButton: indent en styling subcontent

---

CHANGELOG.md
packages/core/src/components/map-controls/map-controls.scss

#3130 [Fixed] Map Controls: bij inzoomen heeft de knop kaartlagen geen accessible name meer

---

CHANGELOG.md
packages/core/src/components/alert/alert.scss
packages/dso-toolkit/src/components/alert/alert.scss

Ik heb de css moeten verplaatsen naar de dso-toolkit folder, zoals bij `banner.scss` het geval is. De `set-colors.apply` sass functie lijkt anders niet goed te werken.

#3168 [Fixed] Alert: Icon bij de link heeft de verkeerde kleur in core variant

---

CHANGELOG.md
angular-workspace/components/badge/badge.stories.ts
packages/core/src/components/advanced-select/advanced-select.interfaces.ts
packages/core/src/components/advanced-select/advanced-select.scss
packages/core/src/components/advanced-select/advanced-select.tsx
packages/core/src/components/badge/badge.interfaces.ts
packages/core/src/components/badge/readme.md
packages/dso-toolkit/src/components/advanced-select/advanced-select.models.ts
packages/dso-toolkit/src/components/advanced-select/advanced-select.variables.scss
packages/dso-toolkit/src/components/badge/badge.args.ts
packages/dso-toolkit/src/components/badge/badge.mixins.scss
packages/dso-toolkit/src/components/badge/badge.models.ts
packages/dso-toolkit/src/components/badge/badge.stories-of.ts
packages/dso-toolkit/src/components/badge/badge.variables.scss
packages/react/src/components/badge/badge.stories.tsx
storybook/cypress/fixtures/image-snapshot-components.json
storybook/src/components/badge/badge.core-stories.ts
storybook/src/components/badge/badge.css-stories.ts
storybook/src/example-pages/zoeken-in-lijst-cards.stories.ts
website/blog/2025-06-16-dso-toolkit-74.0.0.mdx

- Info label heeft een nieuwe kleur, dus 2 diffs in HTML en Core
- Danger label is verwijderd, dus 2 errors in HTML en Core dat de snapshot niet meer matchen 

#3170 [Changed] Badge: Verwijderen danger variant en kleuraanpassing info variant

---

CHANGELOG.md
storybook/src/components/accordion/accordion.css-template.ts

#3221 [Task] Accordion Section: Button in Section Handle kleurt grasgroen als Section open is

---

CHANGELOG.md
packages/core/src/components/card/readme.md

#3285 [Task] Card: Afbeelding in Storybook Docs wordt niet getoond
